### ISSUE TITLE
how to get participant information when use examples/voice-pipeline-agent?

### ISSUE THREAD

**Issue by ericyue** [livekit/agents#1012]
I want to get the sip caller number in voice assistant example, is there a way to do that?  i can not find any information about participant related code in the example. how to access it?

**Comment by martin-purplefish** [comment]
`ctx.room.on()` lets you to subscribe to different events: https://github.com/livekit/python-sdks/blob/5b78bcc816d9254be7b82421be2d18b80531335a/livekit-rtc/livekit/rtc/room.py#L224

**Comment by ericyue** [comment]
thank you martin, I will give it a try.

**Comment by davidzhao** [comment]
@ericyue we've just published docs that should help: https://docs.livekit.io/sip/examples/sip-participant-attributes/
