### ISSUE TITLE
Issue: Jobs keep enqueued, even for empty rooms

### ISSUE THREAD

**Issue by Kedaqusa1604** [livekit/agents#1024]
Hi. Livekit team. I hope this message finds you well.

I would like to report a behavior that I noticed, which may indicate a possible bug:

When there are no workers available, the jobs are enqueued, and as soon as workers become available, these jobs are assigned to them. However, I observed that jobs that do not have associated users are being assigned to workers. Is this the expected behavior?

Here are some session IDs that exhibited this behavior:

- RM_PN67Yt9ePuKL
- RM_ra4Hhth49Bod
- RM_WKEcLVhppvjC

Here are the steps that I used in my test, if you want to reproduce this issue:

- set the worker options to `load_threshold=0.65` and the load_fnc to a function that returns the cpu usage
- execute `python agent-worker.py start`
- run as many [playgrounds](https://agents-playground.livekit.io/) as possible til the worker is full. Don't close any of these.
- run a last one playground. If the worker is full, you'll notice in the interface that the audio keeps loading (save the room name, you'll need it for the logs):
![{75AA7F1C-2844-4845-AB35-66936E62FBFB}](https://github.com/user-attachments/assets/43d27d14-ce88-4ad0-ad75-0e386f9898f8)
- wait for a time (lets say 10-20 seconds) and close the last playground. Close the other ones.
- In the session logs in the livekit cloud console, search the record with the room name that you saved earlier. You'll see something like this:
![image](https://github.com/user-attachments/assets/72778bc5-8f10-4921-bd68-cc8ac9b72df2)

Thanks in advance for your attention, let me know if you need any additional details or clarification.

**Comment by davidzhao** [comment]
@Kedaqusa1604 this is expected. The room remains open for 30s (default departureTimeout) after the user leaves the room.

So even though the user left shortly before then. The room is still open. So when the worker has gained sufficient capacity so that an agent was dispatched to it.
