### ISSUE TITLE
how to make the demo agent to exit the room (hang up a SIP call)  when use examples/voice-pipeline-agent? 

### ISSUE THREAD

**Issue by ericyue** [livekit/agents#1033]
How can I make the demo agent to exit the room (hang up a SIP call) automatically when they receive a message like 'byebye'? from user? " 
I use examples/voice-pipeline-agent for a phone agent demo.  any help will be appreciate

**Comment by ericyue** [comment]
the situation is like :
user: thant'sall,byebye
agent:  ok,goodbye
agent: [disconnect from room/hang up sip call]

**Comment by davidzhao** [comment]
https://docs.livekit.io/agents/build/session/#disconnecting-everyone

**Comment by ericyue** [comment]
> https://docs.livekit.io/agents/build/session/#disconnecting-everyone

I have test this method , but the call not hangup .  why the room is deleted but the phone call is still exists? how to do a hangup by agent?
