### ISSUE TITLE
Video Track Memory Consumption during a conversation

### ISSUE THREAD

**Issue by claudioc8211** [livekit/agents#1058]
Hi thanks to all who will reply to this question.
Right now I'm using VideoTrack to pass an image to the LLM for some basic analysis. What happens is that after used a screenshot taken from the stream, I see that the RAM memory consumption continue to raise till the machine blows up. It seems like the agent continue to collect images from the VideoTrack and store them into memory without cleaning it until a disconnection is performed.
My code is:

    `async def process_video_frame(user_msg: str, context: AgentCallContext, source: rtc.TrackSource):

    latest_image: rtc.VideoFrame | None = None

    if context.agent._room.connection_state == rtc.ConnectionState.CONN_CONNECTED:
        video_track = await get_video_track(context.agent._room, source)

        async for event in rtc.VideoStream(video_track):
            # We'll continually grab the latest image from the video track
            # and store it in a variable.
            if event.frame:
                latest_image = event.frame
                break
        
        if latest_image:
            await image_analysis(user_msg, latest_image, context)`

get_video_track function:

    `async def get_video_track(room: rtc.Room, source: rtc.TrackSource) -> rtc.RemoteVideoTrack:
    video_track = asyncio.Future[rtc.RemoteVideoTrack]()
    for _, participant in room.remote_participants.items():
        logger.info(f"Processing participant: {participant._info}")
        for _, track_publication in participant.track_publications.items():
            logger.info(f"Processing track publication: {track_publication}")
            
            if track_publication.source == source:
                logger.info(f"Track Source: {track_publication.source}")
                track = track_publication.track
            
                if track is None or not isinstance(track, rtc.RemoteVideoTrack):
                    continue
                video_track.set_result(track)
                break
            else:
                logger.info(f"Track Source: {track_publication.source} does not match {source}")

    if not video_track.done():
        raise ValueError(f"No {source} track found in the room")
        
    return await video_track`

And finally image_analysis function:

    `async def image_analysis(user_msg: str, image: rtc.VideoFrame, context: AgentCallContext):
    """Process the latest image and append it to the chat context, then call the LLM."""
    
    # Copy the chat context and append the user message and image
    chat_ctx = context.agent.chat_ctx.copy()
    chat_image = ChatImage(image=image)
    chat_ctx.append(
        text=user_msg,
        images=[chat_image], 
        role='user')

    # Send the analysis result back to the user
    llm_stream = context.agent.llm.chat(chat_ctx=chat_ctx)
    await context.agent.say(llm_stream)
    context.store_metadata("is_analyzing_image", False)`

How can I stop to collect stream from the track after the image_analysis and clean the RAM memory?

I'm working with:
"livekit==0.17.5",
  "livekit-agents>=0.10.2",
  "livekit-api>=0.7.0",
  "livekit-plugins-azure>=0.3.1",
  "livekit-plugins-elevenlabs>=0.7.3",
  "livekit-plugins-openai>=0.10.4",
  "livekit-plugins-silero>=0.7.2",

**Comment by davidzhao** [comment]
the issue here is you are creating a stream without closing it for each frame. Streams need to be manually closed, so instead of:

```
async for event in rtc.VideoStream(video_track):
```

you should do the following to ensure it's closed:

```
stream = rtc.VideoStream(video_track)
async for event in stream:
    ....
await stream.aclose()
```

related, your code seems inefficient in creating a stream for each call of the frame. it'd be better to just have a coroutine that reads from a single stream and saving the last frame.
