### ISSUE TITLE
Let the user decide if they can interrupt

### ISSUE THREAD

**Issue by zhanghx0905** [livekit/agents#1068]
Interrupting conversations is a useful feature. But sometimes the user is in a noisy environment and background sounds can be misrecognized as interruptions. It should be someway to leave user to decide whether to enable interruptions or not.

**Comment by jayeshp19** [comment]
You can turn it off by `allow_interruptions=False`

**Comment by zhanghx0905** [comment]
> You can turn it off by `allow_interruptions=False`

I wander can Room Participants choose for themselves whether or not to interrupt? For example users of https://github.com/livekit/agents-playground

**Comment by davidzhao** [comment]
this is enabled on the agent-side. To control it from clients, you can use [participant attributes](https://docs.livekit.io/home/client/data/participant-attributes/).

**Comment by zhanghx0905** [comment]
> this is enabled on the agent-side. To control it from clients, you can use [participant attributes](https://docs.livekit.io/home/client/data/participant-attributes/) to signal your agent how it should behave

How can I get `canUpdateOwnMetadata` permission?
