### ISSUE TITLE
Why is the code in agent/livekit-plugin/livekit-plugin-openai different from the code installed via pip install livekit-plugin-openai?

### ISSUE THREAD

**Issue by harmlessman** [livekit/agents#1070]
I am studying these codes to develop a custom plugin. One thing I am curious about is that the code installed via pip and the source code in the repository are similar but have slight differences. When I modify and use the repository's source code during development, I often encounter various errors. How can I modify and use the source code in the repository to develop a custom plugin effectively?

**Comment by davidzhao** [comment]
like most projects, there are released versions (what's installed with pip install) from the source tree. the differences you observe is simply that.

for local development, you can `pip install -e <path-to-package>`

**Comment by harmlessman** [comment]
Thank you, I think I was confused for a moment because the name of the core function was different.
