### ISSUE TITLE
TTS broken and jittery audio

### ISSUE THREAD

**Issue by martin-purplefish** [livekit/agents#1077]
I'm not sure of a better title, but we are seeing what sounds like either:

* Two streams playing at once (my leading hypothesis)
* Re-ordered frames.

I've attached example audio showing this (using Cartesia), but I don't know whether this is specific to them. The Cartesia team believes it's at the orchestration layer. We've heard ones that are much longer periods of weird audio than this clip, which makes me suspect it's _not_ a networking related issue.

https://github.com/user-attachments/assets/7a638dfb-0314-4328-82d6-75d5b71306ba

The full transcript for this message is

```
Well Dylan, you are ahead of the curve, at least as far as humans go. In that case, we can skip the small talk and get down to business. I have about 4 questions. This is meant to be informal, so be yourself, have some fun with it, and you can keep your answers brief. It should take less than 10 minutes. Sounds good?
```

And if you listen - the glitch is it saying "Sounds good?" over top of the other sentence.

**Comment by davidzhao** [comment]
@shershah1024 which TTS provider are you using?

**Comment by shershah1024** [comment]
Azure, and I just noticed that it happens only with non english languages. Spanish in my case

**Comment by davidzhao** [comment]
interesting insight, we'll investigate

**Comment by jayeshp19** [comment]
@martin-purplefish @shershah1024 Are you encountering this issue frequently? Is there a way for me to replicate it?

**Comment by shershah1024** [comment]
I tested it again just now.  The issue no longer exists, and I haven't changed anything in a couple of days :D. I will check if it persists and update, and probably even get a recording

**Comment by jayeshp19** [comment]
It seems there's an issue on Cartesia side. I tried making a request on their website's playground with the input: "Certainly! Here are five asterisks: *****. If there's anything else you'd like to discuss or explore, just let me know!" and it breaks (says * more than 5 times and skips sentences after the asterisks. )
https://play.cartesia.ai/text-to-speech

**Comment by martin-purplefish** [comment]
I also haven't been able to reproduce lately, so I think Cartesia fixed it. I'll re-open if we run into this again.

**Comment by theomonnom** [comment]
Thanks, please let us know!
