### ISSUE TITLE
Issue: AttributeError: module 'livekit.agents.metrics' has no attribute 'PeriodicCollector' in livekit-plugins-deepgram 0.6.10

### ISSUE THREAD

**Issue by erkansaldir** [livekit/agents#1093]
Issue Report: LiveKit Deepgram Plugin Error in Version 0.6.10

Error Summary:
AttributeError: module 'livekit.agents.metrics' has no attribute 'PeriodicCollector'

Problem Description:
When using livekit-plugins-deepgram version 0.6.10, the system encounters an AttributeError indicating that the PeriodicCollector is missing from the metrics module. This error prevents the STT (Speech-to-Text) functionality from initializing properly.

Key Error Message:
AttributeError: module 'livekit.agents.metrics' has no attribute 'PeriodicCollector'

Environment Details:
- livekit: 0.18.1
- livekit-agents: 0.11.2
- livekit-plugins-deepgram: 0.6.10 (problematic version)
- livekit-plugins-openai: 0.10.7
- livekit-plugins-silero: 0.7.3
- Python: 3.11

Detailed Error Log:
2024-11-16 08:52:36,008 - livekit.agents - DEBUG - http_session(): creating a new httpclient ctx
2024-11-16 08:52:36,009 - livekit.agents.pipeline - ERROR - Error in _recognize_task
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/livekit/agents/utils/log.py", line 16, in async_fn_logs
return await fn(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/livekit/agents/pipeline/human_input.py", line 100, in _recognize_task
stt_stream = self._stt.stream()
^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/livekit/plugins/deepgram/stt.py", line 249, in stream
return SpeechStream(self, config, self._api_key, self._ensure_session())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/livekit/plugins/deepgram/stt.py", line 284, in init
self._audio_duration_collector = metrics.PeriodicCollector(
^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'livekit.agents.metrics' has no attribute 'PeriodicCollector'

Resolution:
Downgrading livekit-plugins-deepgram to version 0.6.9 resolves the issue. The system functions correctly with this earlier version.

Steps to Reproduce:
1. Install livekit-plugins-deepgram version 0.6.10
2. Initialize STT with Deepgram
3. Attempt to create a speech stream
4. Observe AttributeError for missing PeriodicCollector

Steps to Resolve:
1. Downgrade livekit-plugins-deepgram:
```bash
pip install livekit-plugins-deepgram==0.6.9

Restart the application

Additional Notes:

The error appears to be introduced in version 0.6.10
No other package versions needed to be modified
The issue specifically relates to the metrics collection functionality in the Deepgram plugin
Version 0.6.9 remains stable and functional
The error occurs when attempting to initialize the speech recognition stream
The missing PeriodicCollector class in the metrics module suggests a possible dependency issue or incomplete implementation in version 0.6.10

Impact:
The error prevents the speech-to-text functionality from initializing, making the voice assistant feature completely non-functional when using version 0.6.10.
Copy CopyRetryClaude does not have the ability to run the code it generates yet.Ehata  başlığınıda  yazarmısınEditIssue: AttributeError: module 'livekit.agents.metrics' has no attribute 'PeriodicCollector' in livekit-plugins-deepgram 0.6.10
CopyIssue Report: LiveKit Deepgram Plugin Error in Version 0.6.10

Error Summary:
AttributeError: module 'livekit.agents.metrics' has no attribute 'PeriodicCollector'

Problem Description:
When using livekit-plugins-deepgram version 0.6.10, the system encounters an AttributeError indicating that the PeriodicCollector is missing from the metrics module. This error prevents the STT (Speech-to-Text) functionality from initializing properly.

Key Error Message:
AttributeError: module 'livekit.agents.metrics' has no attribute 'PeriodicCollector'

Environment Details:
- livekit: 0.18.1
- livekit-agents: 0.11.2
- livekit-plugins-deepgram: 0.6.10 (problematic version)
- livekit-plugins-openai: 0.10.7
- livekit-plugins-silero: 0.7.3
- Python: 3.11

Detailed Error Log:
2024-11-16 08:52:36,008 - livekit.agents - DEBUG - http_session(): creating a new httpclient ctx
2024-11-16 08:52:36,009 - livekit.agents.pipeline - ERROR - Error in _recognize_task
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/livekit/agents/utils/log.py", line 16, in async_fn_logs
return await fn(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/livekit/agents/pipeline/human_input.py", line 100, in _recognize_task
stt_stream = self._stt.stream()
^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/livekit/plugins/deepgram/stt.py", line 249, in stream
return SpeechStream(self, config, self._api_key, self._ensure_session())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/livekit/plugins/deepgram/stt.py", line 284, in init
self._audio_duration_collector = metrics.PeriodicCollector(
^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'livekit.agents.metrics' has no attribute 'PeriodicCollector'

**Resolution:**
Downgrading livekit-plugins-deepgram to version 0.6.9 resolves the issue. The system functions correctly with this earlier version.

Steps to Reproduce:
1. Install livekit-plugins-deepgram version 0.6.10
2. Initialize STT with Deepgram
3. Attempt to create a speech stream
4. Observe AttributeError for missing PeriodicCollector

Steps to Resolve:
1. Downgrade livekit-plugins-deepgram:
```bash
pip install livekit-plugins-deepgram==0.6.9

Restart the application

**Additional Notes:**

The error appears to be introduced in version 0.6.10
No other package versions needed to be modified
The issue specifically relates to the metrics collection functionality in the Deepgram plugin
Version 0.6.9 remains stable and functional
The error occurs when attempting to initialize the speech recognition stream
The missing PeriodicCollector class in the metrics module suggests a possible dependency issue or incomplete implementation in version 0.6.10

**Impact:**
The error prevents the speech-to-text functionality from initializing, making the voice assistant feature completely non-functional when using version 0.6.10.

**Comment by mercuryyy** [comment]
Thank you for this was having the same issue.

**Comment by davidzhao** [comment]
sorry, we pushed an update to Deepgram without bumping a dependency's version. will fix this right now

**Comment by erkansaldir** [comment]
Thank you to the LiveKit team for quickly resolving the issue we encountered and providing excellent support. Their swift solution and professional approach are truly commendable. Wishing you continued success!
