### ISSUE TITLE
Can not hang up the phone call when use sip with twilio

### ISSUE THREAD

**Issue by ericyue** [livekit/agents#1144]
I have test this method in issue 1033, but the call can not hangup. 

[https://github.com/livekit/agents/issues/1033](url)

    async def _cleanup_room(self, room_name: str):
        """Clean up the room after the conversation"""
        try:
            bot_logger.info(f"Attempting to delete room: {room_name}")
            await self.api.room.delete_room(api.DeleteRoomRequest(room=room_name))
            bot_logger.info(f"Successfully deleted room: {room_name}")
        except Exception as e:
            bot_logger.error(f"Error deleting room: {e}")

Why the room is deleted but the phone call is still exists? 
how to do a hangup by agent side?

**Comment by ericyue** [comment]
got it

**Comment by duan-nguyen** [comment]
how? i have the same issue..

**Comment by Aillian** [comment]
How to hangup the call?

**Comment by dnlrbz** [comment]
@ericyue how did you solve the issue with hanging up the call in livekit with twilio? Just deleting the room or removing a participand causes and error on the twilio side. Any feedback would be much appreciated.
