### ISSUE TITLE
The memory usage is a bit too much, is there any other way to reduce the memory usage?

### ISSUE THREAD

**Issue by zhushixia** [livekit/agents#1166]
The memory usage is a bit too much, is there any other way to reduce the memory usage?

**Comment by davidzhao** [comment]
what are you seeing as memory usage?

**Comment by zhushixia** [comment]
Every time I add an agent to the room, it consumes about 96M more memory，the default job_executor_type=JobExecutorType.PROCESS is used in ubuntu(I calculate the total memory consumption by adding each process)

worker_options = WorkerOptions(
        agent_name=AGENT_NAME,
        request_fnc=define_request_fnc,
        entrypoint_fnc=entrypoint,
        load_fnc=memory_only_load_function,
        load_threshold=0.9,
        port=8081,
        api_secret=API_SECRET,
        api_key=API_KEY,
        ws_url=WS_URL
    )
    cli.run_app(worker_options)，

But when I set job_executor_type=JobExecutorType.THREAD, the memory not drop when the room is disconnected
