### ISSUE TITLE
Room's max participants value is ignored

### ISSUE THREAD

**Issue by FiddlersCode** [livekit/agents#1184]
**How to replicate**
- create a room using Livekit's RoomServiceClient, setting `maxParticipants` to 2
   - according to [LiveKit docs](https://docs.livekit.io/home/get-started/api-primitives/#participant) an agent is a particpant, so setting max_participants to 2 should allow for one "human" user and one livekit agent.

**Expected behaviour**
Only 1 "human" (remote) participant is allowed to join

**Actual behaviour**
At least 2 "human" (remote) participants are allowed to join plus the Livekit agent.

Versions
livekit-server 0.8.3 (Kotlin)

**Comment by davidzhao** [comment]
this is a timing issue in a sense.

LiveKit is a distributed system. when two different participant connect to livekit at the same time, they might be connecting to entirely different data centers. when that happens, each server doesn't yet know how many participants has connected to the other server.

the information will be eventually consistent. so eventually it will be enforced. at this moment, we are not able to do much about this behavior. Please keep this in mind as you build applications that depend on this enforcement

**Comment by FiddlersCode** [comment]
> this is a timing issue in a sense.
> 
> LiveKit is a distributed system. when two different participant connect to livekit at the same time, they might be connecting to entirely different data centers. when that happens, each server doesn't yet know how many participants has connected to the other server.
> 
> the information will be eventually consistent. so eventually it will be enforced. at this moment, we are not able to do much about this behavior. Please keep this in mind as you build applications that depend on this enforcement

That makes sense, thanks. Can I just check that in the case where more than 2 participants have joined a room with max participants of 2, then:
1. Neither of the "human" participants will be forcibly removed from the room - we'll be able to carry on with 3 participants for the lifetime of the room or until 1 participant leaves?
2. No additional participants will be allowed (except in the case of the timing issue mentioned above)
