### ISSUE TITLE
Please add TTS support to the Deepgram plugin

### ISSUE THREAD

**Issue by jadams777** [livekit/agents#1193]
Hello team. Please add TTS support to the Deepgram plugin. That would be super helpful.

https://github.com/livekit/agents/tree/main/livekit-plugins/livekit-plugins-deepgram

@davidzhao

**Comment by zamia** [comment]
Yeah,  it will be great! if livekit supports it.
We have the same requirement and  so I write a simple plugin, try it if you need. We already use it in our product and it works fine.

The code is here:
https://gist.github.com/zamia/e3f324aaf20babb1350c826ab4bb0bff
It supports the latest version livekit agents.(0.12.1)


Usage: 
```
from deepgram_tts import DepgramTTS

# in your pipeline agent
tts=DeepgramTTS(
            voice=DeepgramVoice(model="aura-luna-en", name="Luna"),
        ),

```

**Comment by davidzhao** [comment]
we have a PR here. it'll be merged in the next day or so
