### ISSUE TITLE
How do I handle errors 

### ISSUE THREAD

**Issue by nbrustein** [livekit/agents#1199]
I'm trying to figure out how to respond when an error occurs. For instance, I've experienced [this error](https://github.com/livekit/agents/issues/1056).

I would expect that I would be able to listen for errors. Something like:

```
model = openai.realtime.RealtimeModel(
    instructions=instructions,
    modalities=["audio", "text"],
)
assistant = MultimodalAgent(
    model=model,
    fnc_ctx=VoiceCoursePracticeFunctionContext(),
)

session = model.sessions[0]
session.on('error', __on_error)
```

But, reading through the code for `RealtimeSession`, it looks like nothing happens in response to an error from the RealtimeApi other that that it is logged. (I'm looking in the handling of the `'error'` event in `_recv_task`).

Am I thinking about this correctly? Is there some way for me to listen to errors and respond?

**Comment by yepher** [comment]
+1 for me too.

Until the root issue is resolved, it would be super helpful to detect when the problem occurs so we can programmatically kick the agent to continue.

I have a use case that uses a lot of function calls, so it gets stuck quite often in the flow. A user has to ask the agent to continue, or, I like to say, "Say it out loud."

**Comment by longcw** [comment]
@nbrustein Is this PR https://github.com/livekit/agents/pull/1200 what you needed?

**Comment by nbrustein** [comment]
> @nbrustein Is this PR #1200 what you needed?

yup. That's what I had in mind.
