### ISSUE TITLE
OpenAI agent cannot properly parse various complex function argument types

### ISSUE THREAD

**Issue by mykola-mokhnach-parloa** [livekit/agents#1208]
Steps to reproduce:
1. Define a new function similar to the example in https://github.com/livekit/agents/blob/c5897c1b79f6d57a72cbf4c92c87a5bd85ad3e5d/examples/multimodal_agent.py#L29
2. Set the function argument type to `Optional[str]` or  `Union[int, type(None)]` or `float | None`
3. Run the pipeline

Actual result:
An exception stack trace is raised because the [build_oai_function_description](https://github.com/livekit/agents/blob/6b4e9039a70b0e6ef050b1db964ef21f39e774c0/livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/_oai_api.py#L86) type support is limited to only (str, int, float, bool), even though the [FunctionContext](https://github.com/livekit/agents/blob/6b4e9039a70b0e6ef050b1db964ef21f39e774c0/livekit-agents/livekit/agents/llm/function_context.py#L116) class is capable of recognizing the above nullable types.

Expected result:
The `build_oai_function_description` mentioned above should be able to properly parse nullable types like ones above.  
For example, we expect `Optional[str]` to be transformed into `["string", "null"]` OpenAI type definition.

**Comment by davidzhao** [comment]
fixed in #1211

**Comment by mykola-mokhnach-parloa** [comment]
Unfortunately the above change does not completely fix the original issue. The build_oai_function_description function remains the same and is still [unable](https://github.com/livekit/agents/blob/57869fcbba3a480963fc1497bc47d8e1f263ecbb/livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/_oai_api.py#L105) to parse optional type definitions. It would be great to have an actual unit test that verifies parsing of above cases and confirms the actual fix.

**Comment by mykola-mokhnach-parloa** [comment]
thanks for your reply @jayeshp19 

I expect the below unit tests to pass (currently some of them fail):

```python
import pytest
from typing import Union, Optional
from inspect import _empty

from livekit.agents.llm import FunctionInfo, FunctionArgInfo
from livekit.agents.llm.function_context import _is_optional_type
from livekit.agents import llm


def test_typing():
    assert _is_optional_type(Optional[int]) == (True, int)
    assert _is_optional_type(Union[str, None]) == (True, str)
    assert _is_optional_type(None | float) == (True, float)
    assert _is_optional_type(Union[str, int]) == (False, None)


@pytest.mark.parametrize(
    "arg_typ",
    [
        int,
        Optional[int],
        None | int,
        Union[None, int],
        Union[str, None],
    ]
)
def test_description_building(arg_typ: type):
    fi = FunctionInfo(
        name='foo',
        description='foo',
        auto_retry=False,
        callable=lambda: None,
        arguments={
            'arg': FunctionArgInfo(
                name='foo',
                description='foo',
                type=arg_typ,
                default=_empty,
                choices=(),
            ),
        }
    )
    assert llm._oai_api.build_oai_function_description(fi) is not None
```
