### ISSUE TITLE
Please use Cartesia's websockets API to reduce latency

### ISSUE THREAD

**Issue by jadams777** [livekit/agents#1232]
It appears that the Cartesia LiveKit plugin is using HTTPS instead of websockets, which adds overheard and latency.  Please use websockets instead. Thank you. 

https://docs.cartesia.ai/api-reference/tts/tts

**Comment by davidzhao** [comment]
that's what we are doing: https://github.com/livekit/agents/blob/main/livekit-plugins/livekit-plugins-cartesia/livekit/plugins/cartesia/tts.py#L343
