### ISSUE TITLE
How to get VAD status within callback or inside `pipeline_agent.py` to inform that user started talking?

### ISSUE THREAD

**Issue by yakhyo** [livekit/agents#1237]
Hi,
Thank you for creating such a amazing tool. I have been using recently and it's pretty amazing. 
I was trying to get status of VAD when user starts speaking so that I can do some other operations until it finish his speech. 

I have updated following part of the code inside `pipeline_agent.py` but I could not get what I expected, it did not trigger my additional function even.

```python
def _on_start_of_speech(ev: vad.VADEvent) -> None:
           # my additional function runs here
            self._plotter.plot_event("user_started_speaking")
            self.emit("user_started_speaking")
            self._deferred_validation.on_human_start_of_speech(ev)
```

I was looking for ways of calling a function or do some more operations when user starts talking. I searched the issues and docs but could not find solution for that.

I would really appreciate any help to tackle above.

**Comment by davidzhao** [comment]
hi @yakhyo, have you tried listening to the `user_started_speaking` event on the agent?

**Comment by yakhyo** [comment]
@davidzhao , thanks for reply.

I tried after you mentioned it but still it does not triggered. I add below skippet into my agent code:
```python
@assistant.on("user_started_speaking")
    async def handle_user_started_speaking():
        vad_param = ctx.proc.userdata.get("vad")
        logger.info(f"User started speaking. VAD parameter: {vad_param}")
```

It did not appear in the logs when run the agent in `dev` mode.

**Comment by yakhyo** [comment]
@davidzhao , I resolved after adding a listening and fixing some minor issues. 
Thank you.
