### ISSUE TITLE
Azure STT ignores the language specified via constructor parameters

### ISSUE THREAD

**Issue by rmonvfer** [livekit/agents#1241]
## Environment
Python 3.12
`livekit-agents==0.12.2`
`livekit-plugins-azure==0.50`

## Issue
I'm currently running a `VoicePipelineAgent` in production using Azure services (Azure OpenAI as an LLM provider and Azure Speech for both STT and TTS). 

I've recently upgraded `livekit-agents` from v0.11.3 to v0.12.2 and upon initial testing, quickly discovered that my speech was not being correctly transcribed when speaking in a language other than English, even if I specify a `language` or `languages` when building the STT. It seems as if the language used for transcription was hardcoded.

## Debugging
I've checked the latest implementation of the [STT Service](livekit-plugins/livekit-plugins-azure/livekit/plugins/azure/stt.py) and, after some debugging, realized that even if the `language` or `languages` parameters are provided, the `auto_detect_source_language_config` parameter in the `speechsdk.SpeechRecognizer` constructor, will always be None if only one language code is provided upon initialization.

## Cause
The culprit seems to be [this condition](https://github.com/livekit/agents/blob/b190ce087cffac6bd9ee0d53b1ba064c58ba46f8/livekit-plugins/livekit-plugins-azure/livekit/plugins/azure/stt.py#L333) in `_create_speech_recognizer`, where it checks if the user provided any language code before creating the `AutoDetectSourceLanguageConfig`:

```python
  auto_detect_source_language_config = None
  if config.languages and len(config.languages) > 1:
      # We never get here if config.languages has length = 1
      auto_detect_source_language_config = (
          speechsdk.languageconfig.AutoDetectSourceLanguageConfig(
              languages=config.languages
          )
      )

  audio_config = speechsdk.audio.AudioConfig(stream=stream)
  speech_recognizer = speechsdk.SpeechRecognizer(
      speech_config=speech_config,
      audio_config=audio_config,
      # This will be None if only one language is provided and the speech recognizer will default
      # to using en-EN instead of the user-provided language
      auto_detect_source_language_config=auto_detect_source_language_config,  # type: ignore
  )
```

## Solution
The easiest fix is to modify the length condition to make sure the `AutoDetectSourceLanguageConfig` is built even if there's only one user-provided language code:

```python
  auto_detect_source_language_config = None
  if config.languages and len(config.languages) >= 1:
      auto_detect_source_language_config = (
          speechsdk.languageconfig.AutoDetectSourceLanguageConfig(
              languages=config.languages
          )
      )
```

## Next steps
What do you think? This is my first issue in this repo and I preferred not to open a PR straight away but I would gladly do so if you think this is the correct approach.

Best Regards,
Ramón

**Comment by davidzhao** [comment]
great catch Ramon, thank you so much for the detailed ticket. I'll fix this right away
