### ISSUE TITLE
agents playground certficate expired

### ISSUE THREAD

**Issue by ChenghaoMou** [livekit/agents#1293]
It seems that the certificate is expired on agents-playground.livekit.io:

Websites prove their identity via certificates, which are valid for a set time period. The certificate for agents-playground.livekit.io expired on 24/12/2024.
 
Error code: [SEC_ERROR_EXPIRED_CERTIFICATE](about:certerror?e=nssBadCert&u=https%3A//agents-playground.livekit.io/&s=badStsCert&c=UTF-8&d=%20#certificateErrorDebugInformation)
 
<img width="862" alt="Screenshot 2024-12-24 at 15 57 41" src="https://github.com/user-attachments/assets/de9aa08c-ffc9-41ca-bcad-8fc33b716a84" />

**Comment by davidzhao** [comment]
thanks for the heads up. this is fixed now
