### ISSUE TITLE
 Is it allowed to create separate workers from 2 machines to handle audio, video separately?

### ISSUE THREAD

**Issue by see2023** [livekit/agents#147]
A worker accepts  agents.AutoSubscribe.VIDEO_ONLY,  
and the other accepts agents.AutoSubscribe.AUDIO_ONLY,
and they can interact via rtc.ChatMessage.

Thanks.

**Comment by keepingitneil** [comment]
Currently no - we should be releasing this functionality soon though. We are talking about it internally.

**Comment by theomonnom** [comment]
Hey, this is now possible by using different namespaces when starting a Worker using the `namespace` parameter https://github.com/livekit/agents/blob/a077030bbd06dfa256f99effec8b239c4529a012/livekit-agents/livekit/agents/worker.py#L61

**Comment by koolgax99** [comment]
Hey @theomonnom, How about if I want to create 2 or more workers for Video only but they handle different ML tasks?
