### ISSUE TITLE
TorchAudio constantly fails due to no backend

### ISSUE THREAD

**Issue by PaulLockett** [livekit/agents#151]
https://github.com/livekit/agents/blob/27ea3c13dc1632a83c11768534bdfa9ffcccfa48/livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/tts.py#L46

The synthesize function does not work because Torchaudio has no available backends. I'm trying to find a workaround.

**Comment by PaulLockett** [comment]
example failure:
`ERROR:root:google speech task failed: Couldn't find appropriate backend to handle uri <_io.BytesIO object at 0x28dd8da90> and format mp3.`

**Comment by PaulLockett** [comment]
More context. even with a backend ( that must be in the OS)  TorchAudio is not optimized to take in bytes see here: https://github.com/pytorch/audio/issues/800

**Comment by keepingitneil** [comment]
torchaudio uses installed libraries on the host to do decoding. If you install ffmpeg on your host it should be resolved.

**Comment by keepingitneil** [comment]
torchaudio has been replaced with pyav in this PR: https://github.com/livekit/agents/pull/182
