### ISSUE TITLE
Adding timestamp (+ customizable logging configuration?) to worker logging 

### ISSUE THREAD

**Issue by gadi-assorthealth** [livekit/agents#186]
Currently, `worker.py` does not offer an easy way to customize log formats, particularly to include timestamps in logs for debugging. This makes it difficult to debug our worker deployment.

**Feature request**
Add logging functionality to allow users to customize the log format, either by allowing users to use custom logger or simply adding another CLI flag to toggle timestamps in logs.

**Questions for maintainers**
- Have you considered adding timestamps to worker logging?
- Is there a specific approach you prefer?

**Comment by keepingitneil** [comment]
Hey Gadi, we now log JSON formatted logs. For one-off extra field, the `extras` kwarg can be used. For a new logger with app-specific context, [LoggerAdapter](https://docs.python.org/3/library/logging.html#logging.LoggerAdapter) is the canonical way.
