### ISSUE TITLE
In Kitt example, eleven labs API throws many time out errors

### ISSUE THREAD

**Issue by PaulLockett** [livekit/agents#218]
### What I expect
When Running the agent I see logs but no errors

### What happens
The repeated error you get while the agent is running:
```bash
ERROR:root:Unhandled message from ElevenLabs: {'message': 'Have not received a new text input within the timeout of 20.0 seconds. Streaming input terminated. Please make sure to either feed the input in the timely manner, or to send the end of input text (empty string "") when done.', 'error': 'input_timeout_exceeded', 'code': 1008}
```

### How to reproduce
Follow the steps to run the kitt example and open her up in the playground.

### Severity

This error happens repeatedly and even after a few seconds of this failure on an unpaid eleven labs account a free account will get banned with this error response:
```bash
ERROR:root:Unhandled message from ElevenLabs: {'message': 'Unusual activity detected. Free Tier usage disabled. If you are using 
a proxy/VPN you might need to purchase a Paid Plan to not trigger our abuse detectors. Free Tier only works if users do not abuse it, for example by creating multiple free accounts. If we notice that many people try to abuse it, we will need to reconsider Free Tier altogether. \nPlease play fair and purchase any Paid Subscription to continue.', 'error': 'detected_unusual_activity', 'code': 1008}
```

**Comment by davidzhao** [comment]
we'll take a look at this. makes sense to tweak the behavior to not trigger this 11labs warning

**Comment by keepingitneil** [comment]
This should no longer be an issue:
- ElevenLabs now supports long running ws connections along with a flush API
- Our VoiceAssistant creates new streams for each response

**Comment by Pedroluces-design12345** [comment]
How to resolve this issue?
