### ISSUE TITLE
agent architecture - recovery from agent shutdown

### ISSUE THREAD

**Issue by aviadr1** [livekit/agents#242]
if an agent (implemented by users of livekit using the python sdk) crashes, then ideally the livekit-backend should continue pinging the agent pool until another agent becomes available.

however this is not the case:
if the agent stops (for instance I am running the agent in my debugger, and stop the debugger to change code),
and then run the agent again, the livekit-backend never calls my agent to rejoin the room.

for a system built with agents to become production-ready, this error recovery mechanism is a must

**Comment by davidzhao** [comment]
@aviadr1 yes, this is a great point.. we are working on automatic recovery capability
