### ISSUE TITLE
Hidden agent can not publish audio track 

### ISSUE THREAD

**Issue by jasonison** [livekit/agents#250]
A hidden agent will not publish its audio track and have other participants subscribe to it. Other real participants do not automatically subscribe to this track and do not receive track publish events. If the agent is marked not hidden / or visible, then the tracks publish correctly and the other participants automatically subscribe to them. I imagine most use cases will be for the agent to be hidden. Is this a bug or by design? For a use case we are looking at, it would be great to have this functionality.

**Comment by theomonnom** [comment]
Hey, a hidden agent can only subscribe. This is by design. If you're agent publishes tracks and you want to hide it, hide it on the frontend
