### ISSUE TITLE
Guide for Integrating Local Microphone Input with Remote GPU Server for ML Processing in LiveKit

### ISSUE THREAD

**Issue by takan1** [livekit/agents#273]
What's the steps to connect local mic and also use remote GPU server that runs ML models (from the audio input from local mic) with livekit cloud or opensource server?

**Comment by keepingitneil** [comment]
If I'm understanding correctly, this is very normal use case for agents! Are you specifically looking for a local microphone in the python sdk (we don't have a guide for this yet) or could you use another one of our client libraries to get the local microphone (i.e. React, iOS, Android, etc)?

For the GPU server, that's where you'd be running your agent. The setup would look similar to this example: https://github.com/livekit/agents/tree/main/examples/speech-to-text
