### ISSUE TITLE
ideo Frame Not Appearing in Livekit Playground on Mac M3 - Agent Status Stuck at "Starting"

### ISSUE THREAD

**Issue by takan1** [livekit/agents#277]
Hi I'm trying to test the playground with agent but the video frame doesn't appear somehow. It shows dark green color on the video section. And Agent connection True but agent status is "starting" forever.
Here is my code for agent. I'm using mac M3.
import logging
from livekit import rtc
from livekit.agents import JobContext, JobRequest, WorkerOptions, cli

WIDTH = 640
HEIGHT = 480

async def entrypoint(job: JobContext):
    room = job.room
    source = rtc.VideoSource(WIDTH, HEIGHT)
    track = rtc.LocalVideoTrack.create_video_track("video", source)
    options = rtc.TrackPublishOptions(source=rtc.TrackSource.SOURCE_CAMERA)
    publication = await room.local_participant.publish_track(track, options)
    logging.info("published track", extra={"track_sid": publication.sid})

async def request_fnc(req: JobRequest) -> None:
    logging.info("received request %s", req)
    await req.accept(entrypoint)

if __name__ == "__main__":
    from dotenv import load_dotenv
    import os

    load_dotenv()

    LIVEKIT_API_KEY = os.getenv("LIVEKIT_API_KEY")
    LIVEKIT_API_SECRET = os.getenv("LIVEKIT_API_SECRET")
    LIVEKIT_URL = os.getenv("NEXT_PUBLIC_LIVEKIT_URL")
    cli.run_app(WorkerOptions(request_fnc=request_fnc, api_key=LIVEKIT_API_KEY, api_secret=LIVEKIT_API_SECRET,ws_url=LIVEKIT_URL))

Could someone help?

**Comment by keepingitneil** [comment]
I broke agent state (which is just metadata) when we switched to the VoiceAssistant class. Working on a fix for that, but it should have no affect on video.

The dark green color means it's working! The simple example: `COLOR = bytes([0, 255, 0, 255])` publishes a solid green color (R,G,B,A).
