### ISSUE TITLE
The lastest livekit-plugins-silero~=0.4.dev1 doesn't yet publish to https://pypi.org/project/livekit-plugins-silero ! it causing "TypeError: silero_vad() got an unexpected keyword argument 'use_onnx'"

### ISSUE THREAD

**Issue by Nicj228** [livekit/agents#278]
@dsa @paulwe @davidliu @cacheonly @davidzhao

**Comment by maik-parloa** [comment]
Experienced the same issue. Currently working around this by skipping the `download-files` step in the Dockerfile: https://github.com/livekit/agents/blob/main/examples/voice-assistant/Dockerfile#L44

Then downloaded the JIT model separately and instantiated the VAD explicitly by pointing to the local model:
```python
vad=silero.VAD(model_path="models/silero_vad.jit"),
```

**Comment by davidzhao** [comment]
https://github.com/livekit/agents/issues/284
