### ISSUE TITLE
My playground is not voice and can't talk with agent

### ISSUE THREAD

**Issue by MichaelYang1995** [livekit/agents#293]
When I was running the worker locally, I encountered an issue where it was impossible to conduct agent conversations. After debugging, it was discovered that within the "silero/vad.py" file, the method "_dispatch_event" consistently failed to create "agents.vad.VADEvent".

Subsequently, the issue was identified to be related to the VADEventType, as illustrated in the figure.
wait for help @davidzhao

![问题图1](https://github.com/livekit/agents/assets/43946740/6aec3277-c5cc-461c-9929-9abe8af099e5)
![image](https://github.com/livekit/agents/assets/43946740/12bd60f4-5b25-4c1a-af08-993c63b07d08)
![image](https://github.com/livekit/agents/assets/43946740/e7019300-d2e2-444a-b8d7-38c6e1650492)

**Comment by MichaelYang1995** [comment]
<img width="525" alt="image" src="https://github.com/livekit/agents/assets/43946740/5ec0d049-2f6e-47eb-90b9-96737848844a">

The versions of my installed packages are as mentioned above.

**Comment by readerek** [comment]
Could share the solutions?
