### ISSUE TITLE
seems only use English?

### ISSUE THREAD

**Issue by tianmala** [livekit/agents#302]
Can I use other languages talk to this?

**Comment by keepingitneil** [comment]
Language configuration for STT is supported. For example: [deepgram](https://github.com/livekit/agents/blob/main/livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/stt.py#L52)

Similarly, TTS language is also supported in the tts implementations. For example: [elevenlabs](https://github.com/livekit/agents/blob/main/livekit-plugins/livekit-plugins-elevenlabs/livekit/plugins/elevenlabs/tts.py#L78) can switch from the turbo_v2 model to one of their multilingual models.

In our testing, 11labs multilingual is a bit slow - you may have more success with OpenAI's TTS
