### ISSUE TITLE
deepgram connection failed

### ISSUE THREAD

**Issue by MichaelYang1995** [livekit/agents#304]
Has anyone encountered this problem?

`{"asctime": "2024-05-20 20:00:29,659", "level": "WARNING", "name": "livekit.plugins.deepgram", "message": "deepgram connection failed, retrying in 2s", "job_id": "AJ_oRch8GR9fxqf", "pid": 99836}`

`{"asctime": "2024-05-20 20:00:31,663", "level": "INFO", "name": "livekit.plugins.deepgram", "message": "connecting to deepgram url wss://api.deepgram.com/v1/listen?model=nova-2-general&punctuate=true&smart_format=true&interim_results=true&encoding=linear16&sample_rate=48000&vad_events=true&channels=1&endpointing=0&language=en-us", "job_id": "AJ_oRch8GR9fxqf", "pid": 99836}
`

`{"asctime": "2024-05-20 20:00:29,662", "level": "ERROR", "name": "livekit.plugins.deepgram", "message": "deepgram Exception.with_tracebackTraceback (most recent call last):\n  File \"/Users/yangqingyuan/anaconda3/lib/python3.11/site-packages/aiohttp/connector.py\", line 1025, in _wrap_create_connection\n    return await self._loop.create_connection(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/yangqingyuan/anaconda3/lib/python3.11/asyncio/base_events.py\", line 1085, in create_connection\n    raise exceptions[0]\n  File \"/Users/yangqingyuan/anaconda3/lib/python3.11/asyncio/base_events.py\", line 1069, in create_connection\n    sock = await self._connect_sock(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/yangqingyuan/anaconda3/lib/python3.11/asyncio/base_events.py\", line 973, in _connect_sock\n    await self.sock_connect(sock, address)\n  File \"/Users/yangqingyuan/anaconda3/lib/python3.11/asyncio/selector_events.py\", line 634, in sock_connect\n    return await fut\n           ^^^^^^^^^\n  File \"/Users/yangqingyuan/anaconda3/lib/python3.11/asyncio/selector_events.py\", line 674, in _sock_connect_cb\n    raise OSError(err, f'Connect call failed {address}')\nTimeoutError: [Errno 60] Connect call failed ('38.104.135.211', 443)\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/Users/yangqingyuan/anaconda3/lib/python3.11/site-packages/livekit/plugins/deepgram/stt.py\", line 228, in _run\n    ws = await self._session.ws_connect(url, headers=headers)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/yangqingyuan/anaconda3/lib/python3.11/site-packages/aiohttp/client.py\", line 835, in _ws_connect\n    resp = await self.request(\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/yangqingyuan/anaconda3/lib/python3.11/site-packages/aiohttp/client.py\", line 581, in _request\n    conn = await self._connector.connect(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/yangqingyuan/anaconda3/lib/python3.11/site-packages/aiohttp/connector.py\", line 544, in connect\n    proto = await self._create_connection(req, traces, timeout)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/yangqingyuan/anaconda3/lib/python3.11/site-packages/aiohttp/connector.py\", line 944, in _create_connection\n    _, proto = await self._create_direct_connection(req, traces, timeout)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/yangqingyuan/anaconda3/lib/python3.11/site-packages/aiohttp/connector.py\", line 1257, in _create_direct_connection\n    raise last_exc\n  File \"/Users/yangqingyuan/anaconda3/lib/python3.11/site-packages/aiohttp/connector.py\", line 1226, in _create_direct_connection\n    transp, proto = await self._wrap_create_connection(\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/yangqingyuan/anaconda3/lib/python3.11/site-packages/aiohttp/connector.py\", line 1033, in _wrap_create_connection\n    raise client_error(req.connection_key, exc) from exc\naiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.deepgram.com:443 ssl:default [Connect call failed ('38.104.135.211', 443)]\n", "job_id": "AJ_oRch8GR9fxqf", "pid": 99836}`

**Comment by keepingitneil** [comment]
let's keep this discussion in: https://github.com/livekit/agents/issues/303
