### ISSUE TITLE
Ability to perform actions when the session ends

### ISSUE THREAD

**Issue by davidzhao** [livekit/agents#322]
Discussion from Slack:

-----
I'm experimenting with the transcription agent example. It works well, but I'd like to do a bit of post processing after the room ends. I can't figure out where to do this though. It seems like the agent worker is possibly being killed immediately.
I've tried listening on the 'disconnect' event in my agent like this:

```
@job.room.on("disconnected")
async def on_room_disconnect():
    print('disconnected, do work here?')  # this never runs
```
-----

We should ensure that all disconnected callbacks are finished before we terminate the worker process.

**Comment by theomonnom** [comment]
Hey, it is now possible to add a shutdown callback from the JobContext using [JobContext.add_shutdown_callback](https://github.com/livekit/agents/blob/8ce90df03ec2e81dad0a56f66abb21b086704803/livekit-agents/livekit/agents/job.py#L82C9-L82C15)
