### ISSUE TITLE
livekit is not support CentOS 7?

### ISSUE THREAD

**Issue by MichaelYang1995** [livekit/agents#333]
I want to start livekit-agents
I used livekit-cloud.
I start this:
`python3 main.py download-files`
But I meet this error.

`OSError: /home/shared/apps/tutor-livekit-speech/.venv/lib/python3.12/site-packages/livekit/rtc/resources/liblivekit_ffi.so: cannot open shared object file: No such file or directory`

system: 
`Linux version 4.19.104-300.el7.x86_64 (mockbuild@x86-02.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)) #1 SMP Mon Feb 17 15:34:16 UTC 2020`
`CentOS Linux release 7.6.1810 (Core)`

version:
livekit: 0.11.1
livekit-agents:0.6.0

language: 
python3.12

**Comment by xianqiliu** [comment]
@MichaelYang1995 hey, i meet this problem too... how do you fix it?
