### ISSUE TITLE
wait_pc_connection time out

### ISSUE THREAD

**Issue by MichaelYang1995** [livekit/agents#349]
I meet some error.
the pc_connection is always time out.（maybe my free account?）

@davidzhao 
@JARVISMindEngineer

need some help please.

`2024-06-05 16:05:05,356 - livekit - ERROR - livekit_ffi::server::room:200:livekit_ffi::server::room - error while connecting to a room: engine: connection error: wait_pc_connection timed out
2024-06-05 16:05:05,356 - livekit.agents - DEBUG - disconnecting from room
2024-06-05 16:05:05,356 - livekit - ERROR - livekit_ffi::server::room:200:livekit_ffi::server::room - error while connecting to a room: engine: connection error: wait_pc_connection timed out
{"asctime": "2024-06-05 16:05:05,356", "level": "ERROR", "name": "livekit", "message": "livekit_ffi::server::room:200:livekit_ffi::server::room - error while connecting to a room: engine: connection error: wait_pc_connection timed out", "taskName": "Task-13", "job_id": "AJ_6eR7aeYjj2QR", "pid": 22306}
2024-06-05 16:05:05,608 - livekit.agents - ERROR - pipe closed, exiting job
{"asctime": "2024-06-05 16:05:05,608", "level": "ERROR", "name": "livekit.agents", "message": "pipe closed, exiting job", "taskName": "Task-13", "job_id": "AJ_6eR7aeYjj2QR", "pid": 22306}
2024-06-05 16:05:05,608 - livekit.agents - INFO - job process closed
{"asctime": "2024-06-05 16:05:05,608", "level": "INFO", "name": "livekit.agents", "message": "job process closed", "taskName": "Task-13", "job_id": "AJ_6eR7aeYjj2QR", "pid": 22306}`

and sometimes other error
`2024-06-05 17:20:50,914 - livekit.agents - WARNING - assignment for job AJ_4UiBnp38bMBp timed out
{"asctime": "2024-06-05 17:20:50,914", "level": "WARNING", "name": "livekit.agents", "message": "assignment for job AJ_4UiBnp38bMBp timed out", "taskName": "Task-65", "req": "<livekit.agents.job_request.JobRequest object at 0x151d76780>"}
2024-06-05 17:20:50,915 - livekit.agents - ERROR - user request handler for job AJ_4UiBnp38bMBp failed
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yangqingyuan/venv/lib/python3.12/site-packages/livekit/agents/worker.py", line 386, in _user_cb
    await self._opts.request_fnc(req)
  File "/Users/yangqingyuan/PycharmProjects/livekit/main.py", line 65, in request_fnc
    await req.accept(entrypoint)
  File "/Users/yangqingyuan/venv/lib/python3.12/site-packages/livekit/agents/job_request.py", line 127, in accept
    raise exc
  File "/Users/yangqingyuan/venv/lib/python3.12/site-packages/livekit/agents/worker.py", line 429, in _wait_response
    await asyncio.wait_for(wait_assignment, consts.ASSIGNMENT_TIMEOUT)
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/tasks.py", line 519, in wait_for
    async with timeouts.timeout(timeout):
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError
{"asctime": "2024-06-05 17:20:50,915", "level": "ERROR", "name": "livekit.agents", "message": "user request handler for job AJ_4UiBnp38bMBp failed", "exc_info": "Traceback (most recent call last):\n  File \"/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/tasks.py\", line 520, in wait_for\n    return await fut\n           ^^^^^^^^^\nasyncio.exceptions.CancelledError\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/Users/yangqingyuan/venv/lib/python3.12/site-packages/livekit/agents/worker.py\", line 386, in _user_cb\n    await self._opts.request_fnc(req)\n  File \"/Users/yangqingyuan/PycharmProjects/livekit/main.py\", line 65, in request_fnc\n    await req.accept(entrypoint)\n  File \"/Users/yangqingyuan/venv/lib/python3.12/site-packages/livekit/agents/job_request.py\", line 127, in accept\n    raise exc\n  File \"/Users/yangqingyuan/venv/lib/python3.12/site-packages/livekit/agents/worker.py\", line 429, in _wait_response\n    await asyncio.wait_for(wait_assignment, consts.ASSIGNMENT_TIMEOUT)\n  File \"/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/tasks.py\", line 519, in wait_for\n    async with timeouts.timeout(timeout):\n  File \"/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/timeouts.py\", line 115, in __aexit__\n    raise TimeoutError from exc_val\nTimeoutError", "taskName": "Task-66", "req": "<livekit.agents.job_request.JobRequest object at 0x151d76780>"}`

**Comment by theomonnom** [comment]
Hey, is the this [connection test](https://livekit.io/connection-test) working for you?

**Comment by JARVISMindEngineer** [comment]
check your network first. use google cloud computing server or some others which can access frameworks normally.

or you can write some code before run __main__: 

```python
if __name__ == "__main__":
    try: 
        response = requests.get('https://google.com')
        print('google: %d ' % response.status_code)

        response_openai = requests.get('https://openai.com')
        print('openai: %d' % response_openai.status_code)
    except Exception as e: 
        print(e)

    cli.run_app(WorkerOptions(request_fnc))
```

and if you need set local proxy: `os.environ['http_proxy'] = 'http://proxy_host:proxy_port'` also set `https_proxy`;
