### ISSUE TITLE
Worker doesn't receive signal about joining to the room.

### ISSUE THREAD

**Issue by vlxdisluv** [livekit/agents#376]
I faced a problem where, when I create a room and join it from the client, the agent doesn't connect to this room.

When I follow the documentation and create an access token, everything works fine. However, I want to provide some additional data in the "metadata" parameter, which should be invoked before the agent initialization to perform some logic with this data.

I am creating the room like this:
```
async execute(command: {userId: string, agentId: string}): Promise<string> {
  const { userId, agentId } = command;
    
  const createdRoom = await this.livekitService.createRoom({
    name: `test-call-${userId}`,
  });

  const roomAccessToken = await this.livekitService.getAccessTokenForDedicatedRoom(createdRoom.name);
  
  return roomAccessToken;
}
```

After creating the room and utilizing the provided access token on the client side, the client successfully connects, but the agent creation is not triggered. How should I manage this? Could you help with any ideas?

LivekitService details:
```
port { AccessToken, CreateOptions, Room, RoomServiceClient } from 'livekit-server-sdk';

class LivekitService {    
  public async getAccessTokenForDedicatedRoom(roomName: string): Promise<string> {
    const { apiKey, apiSecret } = this.options;

    const at = new AccessToken(apiKey, apiSecret, {
      identity: 'human_user',
      ttl: '10m',
    });

    at.addGrant({
      room: roomName,
      roomJoin: true,
      canPublish: true,
      canPublishData: true,
      canSubscribe: true,
    });

    return at.toJwt();
  }

  public async createRoom({
    name,
    emptyTimeout = 60,
    metadata,
    maxParticipants = 2,
    ...rest
  }: CreateOptions): Promise<Room> {
    const { host, apiKey, apiSecret } = this.options;

    const roomClient = new RoomServiceClient(host, apiKey, apiSecret);

    const room = await roomClient.createRoom({
      name,
      metadata,
      emptyTimeout,
      maxParticipants,
      ...rest,
    });

    return room;
  }
}
```

**Versions**
BE:
livekit-server-sdk: "^1.2.7"

FE:
@livekit/components-react: "^2.3.2",
livekit-client: "^2.2.0",

Livekit Server GO:
livekit-server  1.6.1

**Comment by theomonnom** [comment]
Hey, are you using LiveKit Cloud?

**Comment by theomonnom** [comment]
If you were using OSS, this is going to be fixed with https://github.com/livekit/livekit/pull/2784
I'll double check LiveKit Cloud to make sure this issue doesn't exist there too

**Comment by vlxdisluv** [comment]
Hi, @theomonnom 

Yes, I was using OSS. Thank you for fixing the issue, everything works fine now.

**Comment by ubeytd** [comment]
I am also experiencing this issue in both OSS and Cloud versions.
I have checked so far:
Room is created with JS SDK (agent was joining at this moment).
I am able to list participants, but it's an empty array.
I don't see the room in the active rooms section in the Cloud dashboard.

**Comment by theomonnom** [comment]
Hey, I hotfix was deployed 2 hours ago for Cloud.
