### ISSUE TITLE
AttributeError: module 'livekit.plugins.openai' has no attribute 'LLMStream'

### ISSUE THREAD

**Issue by naman-scogo** [livekit/agents#381]
I am trying to get all the messages in the Chat Context for the Voice Assistant once the room is disconnected. 
I came across the AssistantContext which takes in the assistant and llm _stream as input. 
However, when trying to get the llm_stream using the openai.LLMStream method, this is the error I am getting

**llm_stream = oai.LLMStream()
                 ^^^^^^^^^^^^^
AttributeError: module 'livekit.plugins.openai' has no attribute 'LLMStream'**

This is how I have initialised the assistant and its components

```
from livekit.agents.voice_assistant import VoiceAssistant, AssistantContext
from livekit.plugins import deepgram, elevenlabs, openai, silero

stt = deepgram.STT()
tts = elevenlabs.TTS(model_id='eleven_multilingual_v2', voice=VOICE)
oai = openai
llm=oai.LLM()
llm_stream = oai.LLMStream()
assistant = VoiceAssistant(
        vad=silero.VAD(), # Voice Activity Detection
        stt=stt, # Speech-to-Text
        llm=llm, # Language Model
        tts=tts, # Text-to-Speech
        chat_ctx=initial_ctx, # Chat history context
)
```

then this is how I will be getting the context, and hope to get the messages

```assistant_ctx = AssistantContext(assistant, llm_stream)
   assistant.start(ctx.room)
   assistant_ctx.get_metadata(assisstant, llm_stream)
```

Also, is there a better way to get all the messages in the ChatContext from the llm? Or, wondering even if this the right way?

**Comment by naman-scogo** [comment]
I have recently installed all the new packages from livekit.

`livekit                   0.11.1                   pypi_0    pypi
livekit-agents            0.7.2                    pypi_0    pypi
livekit-api               0.5.0                    pypi_0    pypi
livekit-plugins-deepgram  0.5.1                    pypi_0    pypi
livekit-plugins-elevenlabs 0.6.0                    pypi_0    pypi
livekit-plugins-openai    0.6.0                    pypi_0    pypi
livekit-plugins-silero    0.5.1                    pypi_0    pypi
`

**Comment by theomonnom** [comment]
Hey, this is correct the type should be exposed. Otherwise you don't have to  create a LLMStream manually. Use `oai.LLM().chat `function
