### ISSUE TITLE
typescript（vue） demo

### ISSUE THREAD

**Issue by kknono** [livekit/agents#389]
Hi,

I'm currently working on a project that involves creating a voice assistant using LiveKit. I noticed that most of the examples and documentation are in Python. Could you provide a demo or example of a voice assistant implementation using TypeScript?

Thank you!

**Comment by davidzhao** [comment]
Agents framework is in Python, currently it's not possible to do the same with Node. When Node Agent SDK is available, it'll be available in a new repo
