### ISSUE TITLE
Add Support for OpenAI Assistants API to OpenAI plugin

### ISSUE THREAD

**Issue by skryl** [livekit/agents#396]
**Describe the bug**
The assistants completion API is slightly different from the base model completions api so the `base_url` cannot be simply swapped to the endpoint of an Assistant. 

**To Reproduce**
1. Swap OpenAI plugin `base_url` to an Assistant `base url` formatted as `https://api.openai.com/v1/assistants/{assistant_id}/messages`
2. Attempt to use the assistant for completions
3. Receive stack trace around argument mismatch in `LLM.chat()`

**Expected behavior**
Assistant completions work as expected (similarly to base model completions)

**Comment by umaplehurst** [comment]
This is already available but it's hiding somewhat.

See docs here: https://github.com/livekit/agents/tree/main/livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/beta/README.md
