### ISSUE TITLE
VAD error when running examples/_deployed/kitt/kitt.py

### ISSUE THREAD

**Issue by xushangning** [livekit/agents#402]
The error in the log message:

```python
{"message": "silero stream failed", "exc_info": "Traceback (most recent call last):\n  File \"/app/livekit-plugins/livekit-plugins-silero/livekit/plugins/silero/vad.py\", line 148, in _run\n    await asyncio.shield(self._run_inference())\n  File \"/app/livekit-plugins/livekit-plugins-silero/livekit/plugins/silero/vad.py\", line 171, in _run_inference\n    raw_prob = await asyncio.to_thread(\n               ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/asyncio/threads.py\", line 25, in to_thread\n    return await loop.run_in_executor(None, func_call)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/concurrent/futures/thread.py\", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/app/livekit-plugins/livekit-plugins-silero/livekit/plugins/silero/vad.py\", line 172, in <lambda>\n    lambda: self._model(tensor, self._sample_rate).item()\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/work/.cache/torch/hub/snakers4_silero-vad_master/utils_vad.py\", line 58, in __call__\n    raise ValueError(f\"Provided number of samples is {x.shape[-1]} (Supported values: 256 for 8000 sample rate, 512 for 16000)\")\nValueError: Provided number of samples is 640 (Supported values: 256 for 8000 sample rate, 512 for 16000)", "timestamp": "2024-06-28T10:18:11.088664+00:00"}
```

Formatted:

```python
silero stream failed
Traceback (most recent call last):
  File "/app/livekit-plugins/livekit-plugins-silero/livekit/plugins/silero/vad.py", line 148, in _run
    await asyncio.shield(self._run_inference())
  File "/app/livekit-plugins/livekit-plugins-silero/livekit/plugins/silero/vad.py", line 171, in _run_inference
    raw_prob = await asyncio.to_thread(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/livekit-plugins/livekit-plugins-silero/livekit/plugins/silero/vad.py", line 172, in <lambda>
    lambda: self._model(tensor, self._sample_rate).item()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/work/.cache/torch/hub/snakers4_silero-vad_master/utils_vad.py", line 58, in __call__
    raise ValueError(f"Provided number of samples is {x.shape[-1]} (Supported values: 256 for 8000 sample rate, 512 for 16000)")
ValueError: Provided number of samples is 640 (Supported values: 256 for 8000 sample rate, 512 for 16000)
```

It seems that the error is caused by the release of [Silero VAD v5 model 3 days ago](https://github.com/snakers4/silero-vad/releases). To quote their release note:

> VAD now works with 8 kHz and 16 kHz sample rates, only with fixed 256 and 512 sample windows respectively;

My guess is that all newly deployed agents will be affected by the error, when the v5 model is downloaded from PyTorch Hub.

Mitigation: Download [v4](https://github.com/snakers4/silero-vad/releases/tag/v4.0) and extract it to ~/.cache/torch/hub/snakers4_silero-vad_master. This is where the models downloaded by `torch.hub.load` are saved.

**Comment by gordonchanfz** [comment]
the same error...,how to fix it?

**Comment by Anandsure** [comment]
facing the same issue, is there any way you think we can download the previous release for now as a quick fix?

**Comment by Anandsure** [comment]
`if model_path:
            model = torch.jit.load(model_path)
            model.eval()`
ideally i think we should be able to pass the older V4 release's model_path and load that instead of the defaut load

**Comment by theomonnom** [comment]
Hey, the code was always trying to download the latest version. I've pushed [v0.5.2](https://pypi.org/project/livekit-plugins-silero/0.5.2/) which will download the right silero version. ([branch](https://github.com/livekit/agents/tree/silero-v0.4))

We do have plan to use the new Silero model and we should release a new livekit-agents version next week!

**Comment by Anandsure** [comment]
i see that you've made changes in the __init__.py for the plugin where the model version is specified to v4, but for some reason it doesn't seem to be working.

**Comment by neryabCommitted** [comment]
stuck on this problem too, the update to the init didn't help (deleted the problematic model and re-downloaded the files again)

**Comment by Anandsure** [comment]
@neryabCommitted use silero plugin v5.0.3, it fixes the initialisation in vad.py file to download and USE the v4 model

**Comment by pxz2016** [comment]
use 0.5.3
{"message": "silero stream failed\nTraceback (most recent call last):\n  File \"C:\\Users\\peng\\.conda\\envs\\livekit\\Lib\\site-packages\\livekit\\plugins\\silero\\vad.py\", line 148, in _run\n    await asyncio.shield(self._run_inference())\n  File \"C:\\Users\\peng\\.conda\\envs\\livekit\\Lib\\site-packages\\livekit\\plugins\\silero\\vad.py\", line 171, in _run_inference\n    raw_prob = await asyncio.to_thread(\n               ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\peng\\.conda\\envs\\livekit\\Lib\\asyncio\\threads.py\", line 25, in to_thread\n    return await loop.run_in_executor(None, func_call)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\peng\\.conda\\envs\\livekit\\Lib\\concurrent\\futures\\thread.py\", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\peng\\.conda\\envs\\livekit\\Lib\\site-packages\\livekit\\plugins\\silero\\vad.py\", line 172, in <lambda>\n    lambda: self._model(tensor, self._sample_rate).item()\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\peng/.cache\\torch\\hub\\snakers4_silero-vad_v4.0\\utils_vad.py\", line 65, in __call__\n    ort_outs = self.session.run(None, ort_inputs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\peng\\.conda\\envs\\livekit\\Lib\\site-packages\\onnxruntime\\capi\\onnxruntime_inference_collection.py\", line 220, in run\n    return self._sess.run(output_names, input_feed, run_options)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nonnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(int32)) , expected: (tensor(int64))\n", "job_id": "AJ_Pj4ssaJhz2sv", "pid": 1308, "timestamp": "2024-07-24T01:45:36.384809+00:00"}
