### ISSUE TITLE
Local AI (like ollama etc)

### ISSUE THREAD

**Issue by rvasyar** [livekit/agents#403]
How to use AI LLM models running locally (like ollama, LM studio, any gguf models...) ?
Thx

**Comment by cmurrayis** [comment]
I am also interested in doing this.

**Comment by ralyodio** [comment]
How do I change the base url?

**Comment by davidzhao** [comment]
you can pass it in [like this](https://github.com/livekit/agents/blob/main/livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/llm.py#L284)

**Comment by billyg88** [comment]
Hi, I'm trying to use Ollama for local inference but I cant seem to get the code point to the correct endpoint...

I'm using :

    assistant = VoicePipelineAgent(
        vad=ctx.proc.userdata["vad"],
        stt=deepgram.STT(),
        #llm=openai.LLM(model="gpt-4o-mini"),   !!commented out!!!
        llm = openai.LLM.with_ollama(model="llama3.1",base_url="http://xyz.io:11023/api"),
        tts=openai.TTS(),
        chat_ctx=initial_ctx,
    )
Which points the request to ```/api/chat/completions``` on my  server, I can see the request coming through, but that's not the correct endpoint. 

It should be ```/api/chat```.
It seems like the base_url is always appended with ```/chat/completions``` ?

How do I get around this??

**Comment by billyg88** [comment]
``` 
   assistant = VoicePipelineAgent(
        vad=ctx.proc.userdata["vad"],
        stt=deepgram.STT(),
        #llm=openai.LLM(model="gpt-4o-mini"), !!commented out!!!
        llm = openai.LLM.with_ollama(model="llama3.1",base_url="http://xyz:11023/v1"),
        tts=openai.TTS(),
        chat_ctx=initial_ctx,
    )
```

This is the correct way to request the ollama server --> 
The request is sent to ```/v1/chat/completions``` , ```/chat/completions``` is appended in the openAI code...

**Comment by davidzhao** [comment]
remove `/v1` from your base_url, i.e.

```
base_url="http://xyz:11023"
```

**Comment by koo9** [comment]
> ```
>    assistant = VoicePipelineAgent(
>         vad=ctx.proc.userdata["vad"],
>         stt=deepgram.STT(),
>         #llm=openai.LLM(model="gpt-4o-mini"), !!commented out!!!
>         llm = openai.LLM.with_ollama(model="llama3.1",base_url="http://xyz:11023/v1"),
>         tts=openai.TTS(),
>         chat_ctx=initial_ctx,
>     )
> ```
> 
> This is the correct way to request the ollama server --> The request is sent to `/v1/chat/completions` , `/chat/completions` is appended in the openAI code...

is this working for you? I am also interested in doing the same.
