### ISSUE TITLE
VAD error in silero 5.0.2

### ISSUE THREAD

**Issue by Anandsure** [livekit/agents#405]
> `{"message": "silero stream failed", "exc_info": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/livekit/plugins/silero/vad.py\", line 148, in _run\n    await asyncio.shield(self._run_inference())\n  File \"/usr/local/lib/python3.11/site-packages/livekit/plugins/silero/vad.py\", line 171, in _run_inference\n    raw_prob = await asyncio.to_thread(\n               ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/asyncio/threads.py\", line 25, in to_thread\n    return await loop.run_in_executor(None, func_call)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/concurrent/futures/thread.py\", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/livekit/plugins/silero/vad.py\", line 172, in <lambda>\n    lambda: self._model(tensor, self._sample_rate).item()\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/.cache/torch/hub/snakers4_silero-vad_master/utils_vad.py\", line 58, in __call__\n    raise ValueError(f\"Provided number of samples is {x.shape[-1]} (Supported values: 256 for 8000 sample rate, 512 for 16000)\")\nValueError: Provided number of samples is 640 (Supported values: 256 for 8000 sample rate, 512 for 16000)", "timestamp": "2024-07-02T09:56:29.427859+00:00"}`

I've upgraded the livekit-plugins-silero==0.5.2 , the error is still persistent, im still not sure if it's downloading the right model. I'm running it on a docker container, when i docker exec and check the files seems like it's downloaded the latest release, can we modify the vad.py code to not accept the model path, but always just load the repo and we can explicitly specify v4.

Ps: if possible can we set trust_repo=True

> `UserWarning: You are about to download and run code from an untrusted repository. In a future release, this won't be allowed. To add the repository to your trusted list, change the command to {calling_fn}(..., trust_repo=False) and a command prompt will appear asking for an explicit confirmation of trust, or load(..., trust_repo=True), which will assume that the prompt is to be answered with 'yes'. You can also use load(..., trust_repo='check') which will only prompt for confirmation if the repo is not already trusted. This will eventually be the default behaviour
>   warnings.warn(
> Downloading: "https://github.com/snakers4/silero-vad/zipball/master" to /root/.cache/torch/hub/master.zip`

**Comment by gordonchanfz** [comment]
> >warnings.warn( Downloading: "https://github.com/snakers4/silero-vad/zipball/master" to /root/.cache/torch/hub/master.zip`
note that warings .I change the version numbers in init.py and vad.py to v4.It works now.
![image](https://github.com/livekit/agents/assets/77518307/00a1787c-e6ce-4302-a7ed-dac1201ae2f1)

**Comment by Anandsure** [comment]
`repo_or_dir="snakers4/silero-vad:v4.0", model="silero_vad", onnx=True`
something like this? @gordonchanfz? this is in __init__.py for silero plugin

also my usecase is having it deployed on a docker container

**Comment by gordonchanfz** [comment]
> `repo_or_dir="snakers4/silero-vad:v4.0", model="silero_vad", onnx=True` something like this? @gordonchanfz? this is in **init**.py for silero plugin
> 
> also my usecase is having it deployed on a docker container

yes,aslo need change the version in vad.py.

**Comment by theomonnom** [comment]
Hey, sorry for that, the previous version was changed to only download the v4 of silero. But the main vad.py file was still downloading master.
I've just pushed v0.5.3 rn
