### ISSUE TITLE
Agent on AWS look for local deployment

### ISSUE THREAD

**Issue by Reynold97** [livekit/agents#410]
I am trying to deploy the voice agent examples on EC2, but get stuck looking for local livekit deployment in port 7880.

I am exporting the URL and keys of my cloud project beforehand.

How in the code can I force the agent to initialize with the cloud project?

**Comment by davidzhao** [comment]
are you setting `LIVEKIT_URL` as an env var?

**Comment by Reynold97** [comment]
Yes, that was the solution. Just make a .env and load it from the agent script.
