### ISSUE TITLE
AssertionError: will_create_llm_stream should be a LLMStream

### ISSUE THREAD

**Issue by zhoudaifa007** [livekit/agents#421]
branch: main
cmd:  python minimal_assistant.py start

{"message": "Error in _synthesize_answer_task", "exc_info": "Traceback (most recent call last):\n  File \"/home/agents/myenv/lib/python3.10/site-packages/livekit/agents/utils/log.py\", line 16, in async_fn_logs\n    return await fn(*args, **kwargs)\n  File \"/home/agents/myenv/lib/python3.10/site-packages/livekit/agents/voice_assistant/impl.py\", line 318, in _synthesize_answer_task\n    assert isinstance(\nAssertionError: will_create_llm_stream should be a LLMStream", "timestamp": "2024-07-07T03:07:35.547331+00:00"}
{"message": "Error in _synthesize_answer_task\nTraceback (most recent call last):\n  File \"/home/agents/myenv/lib/python3.10/site-packages/livekit/agents/utils/log.py\", line 16, in async_fn_logs\n    return await fn(*args, **kwargs)\n  File \"/home/agents/myenv/lib/python3.10/site-packages/livekit/agents/voice_assistant/impl.py\", line 318, in _synthesize_answer_task\n    assert isinstance(\nAssertionError: will_create_llm_stream should be a LLMStream\n", "job_id": "AJ_SumC6o8hJk6d", "pid": 52712, "timestamp": "2024-07-07T03:07:35.549820+00:00"}
^C{"message": "draining worker", "id": "AW_GLvzgq28qthW", "timeout": 60, "timestamp": "2024-07-07T03:08:40.350358+00:00"}
{"message": "shutting down worker", "id": "AW_GLvzgq28qthW", "timestamp": "2024-07-07T03:08:40.351340+00:00"}
{"message": "closing job process", "job_id": "AJ_SumC6o8hJk6d", "pid": 52712, "timestamp": "2024-07-07T03:08:40.351546+00:00"}

**Comment by theomonnom** [comment]
Hey, can you try v0.8.0. will_create_llm_stream can now optionally returns None.
