### ISSUE TITLE
start the server agent error with cannot import name 'aio' from 'livekit.agents'

### ISSUE THREAD

**Issue by leejiliang** [livekit/agents#433]
I implemented it step by step according to the Quick Start steps.
In step 3, execute commands :  python main.py download-files  or  python main.py start 
An exception occurs :
![image](https://github.com/livekit/agents/assets/20706241/0a078ef8-e2a6-498c-9e9d-d0247c7b6290)

help me please

**Comment by leejiliang** [comment]
I run the pip install command on branch main of date 2024/07/10

**Comment by davidzhao** [comment]
main branch is not ready for release yet. please use the last released version.

**Comment by leejiliang** [comment]
> main branch is not ready for release yet. please use the last released version.

I did not find the available version in the release column, may I ask which branch can be tried at present, and when the project will release the release version? Thank you for your reply.

**Comment by devdlabs** [comment]
@leejiliang I think he meant, use pip release version rather use git main repo :-)

**Comment by davidzhao** [comment]
> I did not find the available version in the release column, may I ask which branch can be tried at present, and when the project will release the release version? Thank you for your reply.

we are getting close to the next version to be released. it's currently undergoing testing and will land in about a week

**Comment by leejiliang** [comment]
> > main branch is not ready for release yet. please use the last released version.
> 
> I did not find the available version in the release column, may I ask which branch can be tried at present, and when the project will release the release version? Thank you for your reply.

After I switched to the production branch, I followed the tutorial and everything worked fine

**Comment by leejiliang** [comment]
> > I did not find the available version in the release column, may I ask which branch can be tried at present, and when the project will release the release version? Thank you for your reply.
> 
> we are getting close to the next version to be released. it's currently undergoing testing and will land in about a week

Thank you very much for your reply. Looking forward to the release
