### ISSUE TITLE
 LLM.chat() got an unexpected keyword argument  

### ISSUE THREAD

**Issue by devdlabs** [livekit/agents#438]
version: dev(8)
error:  LLM.chat() got an unexpected keyword argument 

` {"message": "Error in _synthesize_answer_task\nTraceback (most recent call last):\n  File \"/home//miniconda3/envs/ava/lib/python3.12/site-packages/livekit/agents/utils/log.py\", line 16, in async_fn_logs\n    return await fn(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home//miniconda3/envs/ava/lib/python3.12/site-packages/livekit/agents/voice_assistant/voice_assistant.py\", line 432, in _synthesize_answer_task\n    await old_task\n  File \"/home//miniconda3/envs/ava/lib/python3.12/site-packages/livekit/agents/utils/log.py\", line 16, in async_fn_logs\n    return await fn(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home//miniconda3/envs/ava/lib/python3.12/site-packages/livekit/agents/voice_assistant/voice_assistant.py\", line 444, in _synthesize_answer_task\n    llm_stream = _default_will_synthesize_assistant_reply(\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home//miniconda3/envs/ava/lib/python3.12/site-packages/livekit/agents/voice_assistant/voice_assistant.py\", line 80, in _default_will_synthesize_assistant_reply\n    return assistant.llm.chat(chat_ctx=chat_ctx, fnc_ctx=assistant.fnc_ctx)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: LLM.chat() got an unexpected keyword argument 'chat_ctx'\n", "job_id": "AJ_RFnUe7QHv22S", "pid": 8958, "timestamp": "2024-07-15T08:28:24.009217+00:00"}`

**Comment by keepingitneil** [comment]
What is the output of `pip list | grep livekit`?

**Comment by keepingitneil** [comment]
the `history` kwarg has been renamed to `chat_ctx` in the 0.8.0 release. Very likely that you have a package version mismatch. Please upgrade your plugins and agent package to the latest
