### ISSUE TITLE
Livekit Agent running on EC2 stopped receiving job requests.

### ISSUE THREAD

**Issue by Anandsure** [livekit/agents#440]
I have a setup running the livekit agent on an EC2 and it's been working for the last couple months. As of today, it's now not receiving any new job requests. 

agent: deployed in us-east-1
EC2 config: no changes in the last 3 months in ALB, Security Groups and so on. it's the same setup
Trying to ping from: india.

is it because there is region aware? and in some change the job request isn't going to my livekit agent deployed in the US?

**Comment by Anandsure** [comment]
update:
so i asked a couple people from the US to connect to it, and they were able to. im confident it's a region thing now, is there a config somewhere where i can chose to accept job Requests from anywhere? or will i need to deploy in multiple regions?

**Comment by davidzhao** [comment]
@Anandsure are you self-deploying LiveKit or using Cloud? If Cloud, which region did you hit that did not dispatch the agent?

**Comment by Anandsure** [comment]
@davidzhao 

it's not self-deployed, i've been using the cloud. 

My agent is in the us-east-1 and when hitting it from anywhere NOT in the united states, the worker wouldn't join the room. 

`{"message": "worker is below capacity, marking as available", "load": 0.0, "threshold": 0.8, "timestamp": "2024-07-18T05:55:12.743919+00:00"}
{"message": "worker is at full capacity, marking as unavailable", "load": 1.0, "threshold": 0.8, "timestamp": "2024-07-18T05:55:52.773877+00:00"}
{"message": "worker is below capacity, marking as available", "load": 0.0, "threshold": 0.8, "timestamp": "2024-07-18T05:55:57.775520+00:00"}
{"message": "worker is at full capacity, marking as unavailable", "load": 1.0, "threshold": 0.8, "timestamp": "2024-07-18T05:58:32.894001+00:00"}
{"message": "worker is below capacity, marking as available", "load": 0.0, "threshold": 0.8, "timestamp": "2024-07-18T05:58:37.895247+00:00"}
{"message": "worker is at full capacity, marking as unavailable", "load": 1.0, "threshold": 0.8, "timestamp": "2024-07-18T06:01:08.009954+00:00"}
{"message": "worker is below capacity, marking as available", "load": 0.0, "threshold": 0.8, "timestamp": "2024-07-18T06:01:13.015605+00:00"}
{"message": "worker is at full capacity, marking as unavailable", "load": 1.0, "threshold": 0.8, "timestamp": "2024-07-18T06:14:58.606026+00:00"}
{"message": "worker is below capacity, marking as available", "load": 0.0, "threshold": 0.8, "timestamp": "2024-07-18T06:15:03.610337+00:00"}
{"message": "worker is at full capacity, marking as unavailable", "load": 1.0, "threshold": 0.8, "timestamp": "2024-07-18T06:15:38.634027+00:00"}
{"message": "worker is below capacity, marking as available", "load": 0.0, "threshold": 0.8, "timestamp": "2024-07-18T06:15:43.638227+00:00"}
{"message": "worker is at full capacity, marking as unavailable", "load": 1.0, "threshold": 0.8, "timestamp": "2024-07-18T06:17:23.721851+00:00"}
{"message": "worker is below capacity, marking as available", "load": 0.0, "threshold": 0.8, "timestamp": "2024-07-18T06:17:28.724138+00:00"}
{"message": "worker is at full capacity, marking as unavailable", "load": 1.0, "threshold": 0.8, "timestamp": "2024-07-18T06:19:28.813878+00:00"}
{"message": "worker is below capacity, marking as available", "load": 0.0, "threshold": 0.8, "timestamp": "2024-07-18T06:19:33.819928+00:00"}
{"message": "worker is at full capacity, marking as unavailable", "load": 1.0, "threshold": 0.8, "timestamp": "2024-07-18T06:20:13.853933+00:00"}
{"message": "worker is below capacity, marking as available", "load": 0.0, "threshold": 0.8, "timestamp": "2024-07-18T06:20:18.857047+00:00"}`

these are consecutive logs on my agent and these timestamps indicate rapid switches, any clue as to whats going on here?

**Comment by akshatvg** [comment]
@davidzhao @davidliu @paulwe @dsa did you have a look at this?

**Comment by davidzhao** [comment]
This was due to a deployment on the Cloud side and has been resolved. Closing.

**Comment by chen-rn** [comment]
I'm running into this as well. Python agent deployed on Railway. Just a series of 

```
worker is below capacity, marking as available

worker is at full capacity, marking as unavailable

worker is below capacity, marking as available

worker is at full capacity, marking as unavailable
```
<img width="562" alt="Screenshot 2024-10-21 at 4 10 53 AM" src="https://github.com/user-attachments/assets/bca1ae8b-9334-4f7d-87f5-67fa75c1ff4c">

**Comment by AphinityApp** [comment]
Seeing the same issue. We isolated it to be region specific because customers can only connect once the worker is migrated to their specific region. For example, if the worker (via livekit cloud) is initialized on East, people on the west coast cannot connect. If the server containing the worker is migrated to west and worker is restarted, vice-versa happens. It started happening all of a sudden, when it was previously working.

**Comment by gajghaten** [comment]
I'm running into the same issue. I'm running LiveKit cloud as well, in us-east-1. Did anyone manage to figure this issue out?

**Comment by davidzhao** [comment]
you need to give the worker instance more resources
