### ISSUE TITLE
Feature: ability to post-process responses from LLM in voice assistant

### ISSUE THREAD

**Issue by davidzhao** [livekit/agents#449]
Sometimes it's desirable to control or change the output from LLMs before TTS.

**Comment by seanmuirhead** [comment]
Similar: https://github.com/livekit/agents/issues/451

**Comment by parshvadaftari** [comment]
@davidzhao I'm still working on the same thing (discussed in slack), but the changes I've made in my code are specific to my requirements and not generalised. I'm not sure if that thing can help you. I'm eagerly waiting for the solution of this.

**Comment by ericyue** [comment]
@theomonnom why this marked as completed?  
can we use this feature now? is there any docs about this? any information will be appreciated:)

**Comment by davidzhao** [comment]
you'd want to use the `before_tts_cb` callback with VoiceAssistant. you can reference this example [here](https://github.com/livekit/agents/blob/main/examples/voice-assistant/custom_pronunciation.py#L24)
