### ISSUE TITLE
Feature request: data_received event listener

### ISSUE THREAD

**Issue by willsmanley** [livekit/agents#532]

**Comment by willsmanley** [comment]
The reason this would be really nice is if you want your client application to send other arbitrary data up that the LLM can use (non-audio, non-video).

**Comment by davidzhao** [comment]
I think you can already do this today, the room object is available to access within the context:

```
async def entrypoint(ctx: JobContext):
  @ctx.room.on("data_received")
  def on_data_received(...):
    pass
```

**Comment by davidzhao** [comment]
all RTC events should be directly accessible within this framework

**Comment by willsmanley** [comment]
oh nice! thanks for the tip
