### ISSUE TITLE
Setting `interrupt_min_words` seems to cause queued agent responses after interruption

### ISSUE THREAD

**Issue by egoldschmidt** [livekit/agents#563]
Settings:
* `interrupt_min_words` set to 2
* Silero VAD + Deepgram STT + Eleven Labs TTS + OpenAI LLM
* All other VoiceAssistant settings use their default values

Steps to repro:
* Begin speaking, and say something that will cause a long response from the agent (eg, "Count backwards from 10")
* Pause and let the audio playback begin
* Quickly ask something else, like what color is the sky

Experienced behavior:
* The first response is read aloud in its entirety
* The answer to my second question is played after the first completes - feeling delayed or duplicated

Expected behavior:
* First audio is cut off and second audio begins shortly after

**Comment by theomonnom** [comment]
Hey, this should be fixed in the new version. Feel free to reopen if you're still able to reproduce this issue
