### ISSUE TITLE
AGENT resource consumption problem

### ISSUE THREAD

**Issue by leejiliang** [livekit/agents#593]
Self-hosted scenario
livekit server 1.6.1 
agent: 0.8.3
CPU: 32
MEM: 64GB
SYS: UBUNTU

steps
1. start livekit server
2. start agent example simple-color
3. use cli create 1000 room

the agent stop at 600+, could't join room anymore
the cpu Busy  99%.
Sys load 1200%.

Why does the agent consume so much CPU resources?

**Comment by davidzhao** [comment]
The agent framework itself consumes very little resource; the resource consumption is all dependent on what the agent is doing.

In this case, your agent is encoding video at 30fps. That is not a trivial amount of work. I'm actually quite impressed that you can handle 600 video publisher on a single machine. that sounds awesome! :)
