### ISSUE TITLE
IndexError: deque index out of range in tts_forwarder on 0.8.5

### ISSUE THREAD

**Issue by egoldschmidt** [livekit/agents#606]
Error report: https://portola.sentry.io/share/issue/f5d6e682fa3f4233ac6da7d3d3472e90/

Is it possible this is just benign logspam from the Eleven Labs plugin closing its connection (`livekit.plugins.elevenlabs.tts.SynthesizeStream is closed`)?

**Comment by theomonnom** [comment]
Hey, sorry for the late reply. I changed how the tts_forwarder is working in this [PR](https://github.com/livekit/agents/pull/706). This shouldn't be an issue anymore
