### ISSUE TITLE
Add support for base64 encoded strings for ChatImage

### ISSUE THREAD

**Issue by willsmanley** [livekit/agents#610]
I put up a quick PR linked below which works with openai plugin, haven't tested if other providers support base64 encoded strings directly.

**Comment by willsmanley** [comment]
hi @davidliu what do you think about enabling images as base64 strings? useful for client-side content that doesn't exist on a URL yet

happy to make any changes if you think this is a good idea

**Comment by davidliu** [comment]
Sorry, I don't really work on the agents side of things, so I can't help here.

**Comment by willsmanley** [comment]
Sorry wrong david! Meant @davidzhao

**Comment by willsmanley** [comment]
dang yall have thought of it all. should have seen that. i will close the pr and the issue.
