### ISSUE TITLE
job is unresponsive, killing job

### ISSUE THREAD

**Issue by leejiliang** [livekit/agents#617]
hello, I don’t know what this ping method is checking. Everything on the livekit server and the agent worker seems to be normal and can respond normally. However, due to the abnormality of this ping, the agent exits unexpectedly. What should I do to avoid this ping timeout exception?

livekit server : 1.6.1
agent: 0.8.3

**Comment by leejiliang** [comment]
![image](https://github.com/user-attachments/assets/a000a902-da89-4151-99fd-5abfaf941fec)

**Comment by davidzhao** [comment]
this happens because you are running blocking operations inside of the agent process. please try using [run_in_executor](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor) for synchronous actions
