### ISSUE TITLE
Google STT crashing- livekit-plugins-google==0.6.2, livekit-agents==0.8.8

### ISSUE THREAD

**Issue by Test-isom** [livekit/agents#683]
{"message": "google stt connection failed, retrying in 0s\nTraceback (most recent call last):\n  File \"/root/pythonenv/enve/lib/python3.10/site-packages/livekit/plugins/google/stt.py\", line 247, in _run\n    await self._run_stream(stream)\n  File \"/root/pythonenv/enve/lib/python3.10/site-packages/livekit/plugins/google/stt.py\", line 295, in _run_stream\n    _streaming_recognize_response_to_speech_data(resp)\n  File \"/root/pythonenv/enve/lib/python3.10/site-packages/livekit/plugins/google/stt.py\", line 344, in _streaming_recognize_response_to_speech_data\n    text += result.alternatives[0].transcript\n  File \"/root/pythonenv/enve/lib/python3.10/site-packages/proto/marshal/collections/repeated.py\", line 125, in __getitem__\n    return self._marshal.to_python(self._pb_type, self.pb[key])\nIndexError: list index out of range", "level": "WARNING", "pid": 652876, "job_id": "AJ_fPuvKmLPFM6y", "timestamp": "2024-08-28T13:53:15.418214+00:00"}

**Comment by davidzhao** [comment]
hi there, this was fixed in #680 and will be released soon!
