### ISSUE TITLE
Container / Deployment / Autoscaling Suggestions?

### ISSUE THREAD

**Issue by willsmanley** [livekit/agents#686]
Has anyone measured cpu/ram requirements for the minimal example?

Anyone done load testing or have recommendations for autoscaling plan?

It'd be good to also know where the sweet spot is: fewer beefy machines with lots of jobs each vs. more lighter machines with fewer jobs each.

I'm going to start testing and will provide any updates here. I believe 2gb ram is minimum required to run a single job.

**Comment by keepingitneil** [comment]
Definitely interested to see your results 🙏 I'm will be writing a best-practices guide soon and had similar plans to do this kind of benchmarking

**Comment by martinnedenn** [comment]
Hello, are there any update or recommendations for this ? Thank you : )

**Comment by Kedaqusa1604** [comment]
Hi. Any updates on this? Thanks in advance

**Comment by davidzhao** [comment]
we've got some deployment docs up now: https://docs.livekit.io/agents/deployment/

as well as example configurations for Fly and ECS: https://github.com/livekit-examples/agent-deployment
