### ISSUE TITLE
TypeError: cannot pickle '_contextvars.Context' object

### ISSUE THREAD

**Issue by cyrilS-dev** [livekit/agents#690]
I'm encountering a `TypeError` in the file `/livekit/agents/ipc/proc_main.py` with livekit-agents version: 0.8.8

This issue occurs in the `_forward_logs` function:

```python
def _forward_logs(self):
    while True:
        record = self._send_q.get()
        if record is None:
            break

        try:
            self._duplex.send_bytes(pickle.dumps(record))
        except duplex_unix.DuplexClosed:
            break

    self._duplex.close()
```
The error is raised because `record` contains a `_contextvars.Context` object, which is not serializable.

**Comment by theomonnom** [comment]
Hey, can you try the above PR to see if the issue is still there.

The code comes from https://github.com/python/cpython/blob/91b7f2e7f6593acefda4fa860250dd87d6f849bf/Lib/logging/handlers.py#L1453
which help forwarding logs when using multiprocessing.Queue

**Comment by cyrilS-dev** [comment]
Hi @theomonnom,

i tried the PR, it doesn't solve the issue.

Here is the full log : 

```
Exception in thread ipc_log_forwarder:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/dev/vocode/vocode-core/.venv/lib/python3.12/site-packages/livekit/agents/ipc/proc_main.py", line 42, in _forward_logs
    self._duplex.send_bytes(pickle.dumps(record))
                            ^^^^^^^^^^^^^^^^^^^^
TypeError: cannot pickle '_contextvars.Context' object
```

**Comment by cyrilS-dev** [comment]
This log is coming from my own app, using livekit-agents, based on [https://github.com/vocodedev/vocode-core/blob/main/apps/livekit/app.py](https://github.com/vocodedev/vocode-core/blob/main/apps/livekit/app.py)

**Comment by theomonnom** [comment]
This is unclear why this is happening, LogRecord shouldn't contain any _contextvars.Context?
Is it possible for you to check which log line is throwing this error? Maybe Vocode is doing something different with logging?

**Comment by cyrilS-dev** [comment]
@theomonnom i spent some time tracking down the error and managed to solve it by adding  `websockets.enableTrace(False) ` into :

```python
async def process(self):
        self.audio_cursor = 0.0
        self.start_ts = now()

        extra_headers = {"Authorization": f"Token {self.api_key}"}
        deepgram_url = self.get_deepgram_url()
        logger.info(f"Connecting to Deepgram at {deepgram_url}")

        try:
            websockets.enableTrace(False)
            async with websockets.connect(deepgram_url, extra_headers=extra_headers) as ws:
```
from [https://github.com/vocodedev/vocode-core/blob/main/vocode/streaming/transcriber/deepgram_transcriber.py](https://github.com/vocodedev/vocode-core/blob/main/vocode/streaming/transcriber/deepgram_transcriber.py)

Not sure why the logs for the websocket of this specific service are causing the issue, though.

**Comment by theomonnom** [comment]
Can I try to use https://github.com/vocodedev/vocode-core/blob/main/apps/livekit/app.py as a minimal reproducible example?

**Comment by cyrilS-dev** [comment]
Sure @theomonnom, you will be able to reproduce the issue. For livekit-agents version 0.8.8, you will have to make some changes : 

```python
if __name__ == "__main__":
    cli.run_app(
            WorkerOptions(
                entrypoint_fnc=entrypoint,
                api_key=os.getenv("LIVEKIT_API_KEY"),
                api_secret=os.getenv("LIVEKIT_API_SECRET"),
                ws_url=os.getenv("LIVEKIT_WS_URL")
            )
        )
``` 
and 
```python
async def entrypoint(ctx: JobContext):
    await ctx.connect()
    configure_pretty_logging()
    output_device = LiveKitOutputDevice()
    ...
```

This part is not required anymore : 
```python
async def request_fnc(req: JobRequest) -> None:
    logger.info("received request %s", req)
    await req.accept(entrypoint)
```

**Comment by theomonnom** [comment]
I was able to reproduce this issue, was tricky to catch, turns out websocket is adding an extra attribute that isn't pickleable

**Comment by cyrilS-dev** [comment]
Thanks for catching that @theomonnom  😅 I applied your modifications, and everything is working perfectly now. I appreciate your help in resolving this issue.
