### ISSUE TITLE
llamaindex example

### ISSUE THREAD

**Issue by ryanleecode** [livekit/agents#692]
is there an integration that uses llamaindex vectors and chatengine directly?

**Comment by theomonnom** [comment]
Hey, I added a bunch of examples in this [PR](https://github.com/livekit/agents/pull/696)

**Comment by ryanleecode** [comment]
> Hey, I added a bunch of examples in this [PR](https://github.com/livekit/agents/pull/696)

You're amazing! 🤩

How would i choose between `query engine` versus `retrieval`? they both try to do the same thing right but in differents ways. could they even be combined?

**Comment by theomonnom** [comment]
Hey, I think it depends, I'm not sure at 100% but you can definitely combine both. You need to experiment by trial and error.

**Comment by rswearin** [comment]
You rock. These examples are great. Thanks.
