### ISSUE TITLE
clicks can be heard with Google TTS

### ISSUE THREAD

**Issue by davidzhao** [livekit/agents#698]
Multiple users reported in slack that click sounds can be heard when Google TTS is in use

With the following package versions

```
livekit-agents==0.8.10
livekit-plugins-google==0.6.3
```

**Comment by AlokYathiraj** [comment]
Having the same issue

**Comment by theomonnom** [comment]
going to take a look at this one today

**Comment by cdrum** [comment]
Thanks for fixing this @theomonnom! do you know how long it usually takes for the new version (0.6.4 in this case) takes to become available for us to install?

cheers!
