### ISSUE TITLE
livekit-plugins-anthropic: Repeated stream text output after function call

### ISSUE THREAD

**Issue by SleepAt11** [livekit/agents#699]
Description:
When using livekit-plugins-anthropic with the voice_assistant agent, I've encountered an issue where the LLM repeats the exact same stream text output after triggering a function call.

Steps to reproduce:
1. Set up a project using livekit-plugins-anthropic and voice_assistant agent
2. Implement a scenario that triggers a function call
3. Observe the LLM's output before and after the function call

Expected behavior:
The LLM should continue generating new, relevant text after the function call.

Actual behavior:
The LLM repeats the exact same stream of text that was output before the function call.

Environment:
- Python version: 3.12.4
- livekit-plugins-anthropic: Installed from latest GitHub code
  (`pip install 'git+https://github.com/livekit/agents.git#subdirectory=livekit-plugins/livekit-plugins-anthropic'`)
- Other relevant dependency versions: 
livekit==0.14.0
livekit-agents==0.8.8
livekit-api==0.7.0
livekit_plugins_elevenlabs==0.7.3
livekit-plugins-deepgram==0.6.5
livekit-plugins-openai==0.8.1
livekit-plugins-silero==0.6.4
livekit-protocol==0.6.0

Additional information:
- I noticed that pip version 0.1.1 doesn't work, which is why I'm using the latest GitHub code.

**Comment by keepingitneil** [comment]
Thanks for the bug report, will look into this today (as well as the deployment issue)
