### ISSUE TITLE
explain "load"

### ISSUE THREAD

**Issue by ryanleecode** [livekit/agents#717]
My worker is starts at load=1 and then flucutates between 0.6 and 0.7 even though i have nothing connected to do it. so my worker can never actually accept jobs because the default threshold is 0.65. i have to change it to 1.

**Comment by keepingitneil** [comment]
Currently load is naively implemented here: https://github.com/livekit/agents/blob/main/livekit-agents/livekit/agents/worker.py#L88

You are free to override it in your WorkerOptions to whatever makes sense for your user case

**Comment by davidzhao** [comment]
@ryanleecode What you are seeing is likely an issue with your local machine being heavily utilized.

For realtime workloads, it's not a good idea to run the session while CPU is running hot. Doing so will temper with thread schedulers which may results in audio being sent later than expected.

When that happens, it would result in an audible glitch. For that reason, we've built in automatic load balancing into the frame work. This is more for when running in production though, so I can definitely see relaxing that when running in dev mode.

**Comment by davidzhao** [comment]
closing this issue, but please do let us know if you have any additional questions.
