### ISSUE TITLE
Agent connect --room command connects to the same room twice

### ISSUE THREAD

**Issue by vanics** [livekit/agents#759]
Hi all, I'm encountering issues while testing agents. The server appears to assign multiple jobs to the same room when using the Agent connect --room command, causing the agent to connect to the room twice.

When making code changes, the situation worsens. Since the script restarts due to being in dev mode (which is okay), it ends up creating multiple jobs, making it extremely difficult to test or consider this functionality for production use.

**Comment by theomonnom** [comment]
Hey, this should have been fixed in the last version of agents
