### ISSUE TITLE
OpenAI timeouts are too low / aren't handled well

### ISSUE THREAD

**Issue by jezell** [livekit/agents#807]
The LLM client is configured with a 5 second read timeout. If the client times out (which it does very often with a short timeout), the stream is not resumed. 

The error handling needs to be more graceful, but the timeout really shouldn't be 5 seconds by default.

**Comment by davidzhao** [comment]
that's a good point.. we set it on the lower side mostly because it would seem awkward in the flow of the conversation to be stuck for awhile. 

but I understand your point, by default it probably should be higher.
