### ISSUE TITLE
KITT-Sourcecode is linked, but missing, 404

### ISSUE THREAD

**Issue by teamgroove** [livekit/agents#809]
I'd really love to have the full-source code and prompts for KITT.

It is linked here: 
https://github.com/livekit/agents-playground/

But it's a 404
https://github.com/livekit/agents/tree/main/examples/kitt

**Comment by keepingitneil** [comment]
We keep our deployed agents in a private repo because it helps with our agility. But KITT is very similar to our minimal-assistant example. I've fixed the link in this PR: https://github.com/livekit/agents-playground/pull/110
