### ISSUE TITLE
Changing tts voice during the conversation

### ISSUE THREAD

**Issue by olivvein** [livekit/agents#810]
Hello, 
I want to change tts voice during the conversation (with a function call) but the VoiceAssistant does not have the ability to update the tts voice while running.
Does anyone have an idea how to achieve that?

**Comment by jezell** [comment]
I think the starting point would be to close the AgentOutput on the VoiceAssistant and then create a new one as a result of the function call.

**Comment by olivvein** [comment]
How to close the agent output?
I have tried to close the assistant to create a new one. But i cannot close the old one.

**Comment by jezell** [comment]
There is an AgentOutput class that gets instantiated by the agent and manages the playback, I believe you'd have to fork the agent but if you close it and create a new one it looks like you can probably change the voice. At least that would likely be the best place to start from what I can see.

**Comment by ChenghaoMou** [comment]
I did something very similar with a modified TTS class. I asked the LLM to include emotions and speed changes during its response generation and update the tts using the `before_tts_cb` callback.

**Comment by davidzhao** [comment]
we are going to make updates cleaner in the framework. Here's how I'm doing it for the voice assistant [we built with Cartesia](https://cartesia-assistant.vercel.app/): https://gist.github.com/davidzhao/5738f0e2d434dea6e5224262ee5c3cfa

**Comment by BaiMoHan** [comment]
> we are going to make updates cleaner in the framework. Here's how I'm doing it for the voice assistant [we built with Cartesia](https://cartesia-assistant.vercel.app/): https://gist.github.com/davidzhao/5738f0e2d434dea6e5224262ee5c3cfa

Hello, do you know how to save the speech and TTS results to files while chatting with the agent?

**Comment by theomonnom** [comment]
Added `update_options` to most TTS in this [PR](https://github.com/livekit/agents/pull/922)
