### ISSUE TITLE
Add Deepgram TTS functionality

### ISSUE THREAD

**Issue by ofa5er** [livekit/agents#842]
Deepgram can do TTS and it is very cheap compared to all other alternatives 1.5$ for 100k characters (vs Elevenlabs 22$ for 100k).

Could you add the TTS support to Deepgram this is not only beneficial from a cost perspective but Deepgram has low latency and also having one provider that offers TTS and STT reduces the overhead of working with different providers.

FYI, Other opensrouce frameworks such as Pipecat supports already deepgram TTS.

**Comment by rahulvk007** [comment]
This would be a great addition if is it added and would be a great help to the community.

**Comment by davidzhao** [comment]
This has been added and released in deepgram plugin 0.6.14: https://pypi.org/project/livekit-plugins-deepgram/

**Comment by hakunamatata1997** [comment]
Hi @davidzhao , I have been trying the same with the version you mentioned above, I still have this error:
`
AttributeError: module 'livekit.plugins.deepgram' has no attribute 'TTS'`

**Comment by fredvollmer** [comment]
Would also be good to have this functionality in the NodeJS SDK.
