### ISSUE TITLE
Function calling seems to be broken in multimodalagent

### ISSUE THREAD

**Issue by willsmanley** [livekit/agents#883]
using the example here, the agent doesn't seem to receive any of the functions in the session configuration: https://github.com/livekit/agents/blob/main/examples/multimodal_agent.py

not sure if this is an issue with the example or the library. thank you in advance for looking!

**Comment by theomonnom** [comment]
![Screenshot 2024-10-10 at 11 06 02 AM](https://github.com/user-attachments/assets/490164c8-9802-409b-9d28-3e148c41dc71)
Hey, it is working for me, any steps to reproduce?

**Comment by willsmanley** [comment]
hey theo, yea i used the example file exactly and it seemed to not be aware of the function

i also tried instantiating a class directly, also no function calling available

maybe i am doing something wrong

```
from __future__ import annotations

import logging
from dotenv import load_dotenv
from livekit.agents import (
    AutoSubscribe,
    JobContext,
    WorkerOptions,
    WorkerType,
    cli,
    llm,
    multimodal,
)
from livekit.plugins import openai
import random

load_dotenv()

logger = logging.getLogger("my-worker")
logger.setLevel(logging.INFO)


class AssistantFnc(llm.FunctionContext):
    @llm.ai_callable(
        description="Returns a random number. You must use this function on every conversation turn and append the number to the end of your response."
    )
    async def generate_random_number(
        self,
    ) -> str:
        return str(random.randint(1, 100))


async def entrypoint(ctx: JobContext):
    logger.info("starting entrypoint")

    fnc_ctx = AssistantFnc()

    await ctx.connect(auto_subscribe=AutoSubscribe.AUDIO_ONLY)
    participant = await ctx.wait_for_participant()

    agent = multimodal.MultimodalAgent(
        model=openai.realtime.RealtimeModel(
            voice="alloy",
            temperature=0.8,
            instructions="You are a helpful assistant",
            turn_detection=openai.realtime.ServerVadOptions(
                threshold=0.6, prefix_padding_ms=200, silence_duration_ms=200
            ),
        ),
        fnc_ctx=fnc_ctx,
    )
    agent.start(ctx.room, participant)


if __name__ == "__main__":
    cli.run_app(WorkerOptions(entrypoint_fnc=entrypoint, worker_type=WorkerType.ROOM))

```

**Comment by ShayneP** [comment]
The issue here isn't that the function call isn't working, but rather that OpenAI doesn't think it should call the function based on the content of your request. It looks like you tried to use some prompt engineering to get this to respond on every call with the number, but this is pretty unreliable with functions.

If you want to test this, add a line to log that the function was called in the `AssistantFnc` class, then ask the agent for a random number. You'll see that in that case, OpenAI will recognize that you need a random number and call your function.

**Comment by BurningLuffy** [comment]
Oh.. I got it.. I need to add chat_ctx to the MultimodalAgent. Thanks
