### ISSUE TITLE
AttributeError: type object 'RealtimeModel' has no attribute 'with_azure' 

### ISSUE THREAD

**Issue by arkodeep3404** [livekit/agents#886]
i am using this code from example:
https://github.com/livekit/agents/blob/main/examples/multimodal_agent.py

but when I try to use azure openai I get this error:

2024-10-10 10:52:21,413 - ERROR livekit.agents - unhandled exception while running the job task
Traceback (most recent call last):
  File "/Users/arkodeepchatterjee/Desktop/today/agent.py", line 57, in entrypoint
    model=openai.realtime.RealtimeModel.with_azure(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'RealtimeModel' has no attribute 'with_azure' {"pid": 59719, "job_id": "AJ_YSAHD5VcBTuf"}
2024-10-10 10:52:21,419 - ERROR livekit.agents - unhandled exception while running the job task
Traceback (most recent call last):
  File "/Users/arkodeepchatterjee/Desktop/today/agent.py", line 57, in entrypoint
    model=openai.realtime.RealtimeModel.with_azure(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'RealtimeModel' has no attribute 'with_azure' {"pid": 59720, "job_id": "AJ_HgwbpMdtmqTU"}

<img width="947" alt="Screenshot 2024-10-10 at 10 52 43 AM" src="https://github.com/user-attachments/assets/d34eb178-003f-4e5b-8556-5de30a81b834">

**Comment by davidzhao** [comment]
this is added in livekit-plugins-openai `0.10.3`, please update and give it another try.

**Comment by arkodeep3404** [comment]
yeah it seems to be working 
thanks a lot

**Comment by arkodeep3404** [comment]
also could you guide me on how to give video access to my agent too?
because currently it only has access to audio

**Comment by theomonnom** [comment]
Hey, let's not mixup issues. Feel free to create new issues
