### ISSUE TITLE
safari web extension

### ISSUE THREAD

**Issue by gedw99** [livekit/agents#887]
Hey,

A safari web extension works on Desktop and Mobile, so quite useful for testing etc.

The current Chrome one is great, but Safari also exists ..

You can see how its done here for an existing Chrome extension.

https://github.com/NomadicDaddy/htmx-debugger/issues/3

Apple made it easy.

**Comment by theomonnom** [comment]
Hey, I'm not sure I understand your issue, can you clarify how this is related to agents?
Feel free to reopen
