### ISSUE TITLE
there is ONLY voice. Often you need to upload. a file or give the AI some text.

### ISSUE THREAD

**Issue by gedw99** [livekit/agents#888]
The https://playground.livekit.io demo is great.

What about being able to also upload files or text ?

Very often you need the AI to read something, and most of the AI system have a file upland feature now.

I see 2 options:

1. Just provide a file upload bottom in the GUI.

2. we are inside a browser, and so the browser can download it ( via your voice command of where the file is ).and then upload it to the AI via its API.  This one is very hard though..

**Comment by theomonnom** [comment]
Hey, this is a nice idea but it isn't in the scope of our demo.
We would appreciate any new community project supporting this feature tho!
