### ISSUE TITLE
TTS sound lagging while text in correctly

### ISSUE THREAD

**Issue by ThangLuuQuoc** [livekit/agents#889]
Livekit agent has a problem with voice is lagging while text in correct 
at 10 second in attach video

https://github.com/user-attachments/assets/a569b48f-c96f-481c-bc6e-f0be3c75c192

**Comment by keepingitneil** [comment]
Agent "transcriptions" timing right now is guessed based on averages. These sort of accuracy issues is a current limitation of the system

**Comment by theomonnom** [comment]
Hey, the transcriptions can get out of sync when there are many unexpected punctuations for voice: like `**Arg #1** `.
You can prompt your LLM to avoid creating lists or any unpronounceable punctuations
