### ISSUE TITLE
[Questions] User Limitation in minimal_assistant.py

### ISSUE THREAD

**Issue by BaiMoHan** [livekit/agents#900]
I have a question regarding the minimal_assistant.py implementation. After starting the script, is it correct that only one user can interact with it at a time? My understanding is that the agent should allow multiple users to chat without interference.

1. Are there parameters available to set a maximum number of concurrent users?
2. Are there any related documents or resources that can guide me in developing a production-ready application?

**Comment by davidzhao** [comment]
each instance of a voice assistant is designed to serve a single user. however, the agent framework makes it easy for you to handle hundreds of thousands of concurrent sessions at the same time.

take a look at these docs: https://docs.livekit.io/agents/overview/

let us know if you have additional questions
