### ISSUE TITLE
Pass arguments to a worker to make initial system prompt more dynamic

### ISSUE THREAD

**Issue by Shoshin23** [livekit/agents#947]
Hello! 

I'm building for a use case where every user of our app can have a slightly different system prompt for their AI agent.

What would be the best way to pass to a worker that I'm spinning up. 

Right now when I try to run `python3 assistant.start --system-prompt=<system-prompt> `I get an error.  

I know this is a naive way of doing it but I'm new to livekit so looking to find a better solution. 

Thanks!

**Comment by theomonnom** [comment]
Hey, I think you could use the environment variables for this purpose.
We currently have no plan to add custom CLI arguments.
